Repository thoth-station/storages, pull requests merged in 2018-12, with the labels that each got.

#396 Release of version 0.9.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#398 Automatic update of dependency boto3 from 1.9.57 to 1.9.58
  Pipfile.lock
Labels: bot

#397 Add index url to the check for Python package version existance
  thoth/storages/graph/janusgraph.py
Labels: size/S

#399 Normalize python package names before every graph operation
  thoth/storages/graph/janusgraph.py
Labels: size/S

#400 Performance index cannot be passed as None
  thoth/storages/graph/janusgraph.py
Labels: size/M

#401 Automatic update of dependency boto3 from 1.9.58 to 1.9.59
  Pipfile.lock
Labels: bot

#402 Automatic update of dependency boto3 from 1.9.59 to 1.9.60
  Pipfile.lock
Labels: bot

#403 Automatic update of dependency boto3 from 1.9.60 to 1.9.61
  Pipfile.lock
Labels: bot

#404 Automatic update of dependency boto3 from 1.9.61 to 1.9.62
  Pipfile.lock
Labels: bot

#405 Automatic update of dependency requests from 2.20.1 to 2.21.0
  Pipfile.lock
Labels: bot

#406 Aggregate hashes from the graph database for the given package
  thoth/storages/graph/janusgraph.py
Labels: size/S

#410 Release of version 0.9.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/L

#411 Automatic update of dependency boto3 from 1.9.62 to 1.9.63
  Pipfile.lock
Labels: bot

#409 Automatic update of dependency thoth-common from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#413 Automatic update of dependency boto3 from 1.9.63 to 1.9.64
  Pipfile.lock
Labels: bot

#415 Extend performance query so it is more generic
  thoth/storages/graph/janusgraph.py
Labels: size/M

#416 Reformat using black
  thoth/storages/__init__.py
  thoth/storages/advisers.py
  thoth/storages/advisers_cache.py
  thoth/storages/analyses.py
  thoth/storages/analyses_cache.py
  thoth/storages/buildlogs.py
  thoth/storages/ceph.py
  thoth/storages/dependency_monkey_reports.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/utils.py
  thoth/storages/inspections.py
  thoth/storages/observations.py
  thoth/storages/provenance.py
  thoth/storages/provenance_cache.py
  thoth/storages/result_schema.py
  thoth/storages/solvers.py
  thoth/storages/sync.py
Labels: size/XXL

#418 ignoring some coala errors
  thoth/storages/ceph.py
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/utils.py
Labels: approved, size/S

#423 Automatic update of dependency cython from 0.29.1 to 0.29.2
  Pipfile.lock
Labels: bot

#420 Automatic update of dependency pytest from 4.0.1 to 4.0.2
  Pipfile.lock
Labels: bot

#424 Automatic update of dependency boto3 from 1.9.65 to 1.9.66
  Pipfile.lock
Labels: bot

#422 Retrieve python package versions using asyncio
  thoth/storages/graph/janusgraph.py
Labels: size/M

#419 Introduce query for querying software stacks
  thoth/storages/graph/janusgraph.py
Labels: size/M

#426 Do not query graph database if no id is provided
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#421 Introduce name for a software stack
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/S, size/XS

#427 Remove unused imports
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#430 Linter fixes
  thoth/storages/graph/janusgraph.py
Labels: size/S

#431 Release of version 0.9.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#432 Automatic update of dependency boto3 from 1.9.66 to 1.9.67
  Pipfile.lock
Labels: bot
