Repository thoth-station/storages, pull requests merged in 2018-08, with the labels that each got.

#64 removing pylint
  Pipfile
Labels: approved, size/XS

#69 Automatic dependency re-locking
  Pipfile.lock
Labels: size/L

#70 Release of version 0.2.0
  thoth/storages/__init__.py
Labels: bot, size/XS

#71 Release of version 0.3.0
  thoth/storages/__init__.py
Labels: bot, size/XS

#72 Release of version 0.4.0
  thoth/storages/__init__.py
Labels: bot, size/XS

#73 Release of version 0.5.0
  thoth/storages/__init__.py
Labels: bot, size/XS

#74 Automatic update of dependency boto3 from 1.7.72 to 1.7.73
  Pipfile.lock
Labels: bot

#75 Automatic update of dependency boto3 from 1.7.73 to 1.7.74
  Pipfile.lock
Labels: bot

#76 Automatic update of dependency boto3 from 1.7.74 to 1.7.75
  Pipfile.lock
Labels: bot

#89 Automatic update of dependency boto3 from 1.7.75 to 1.8.1
  Pipfile.lock
Labels: bot

#92 Automatic update of dependency pytest from 3.7.1 to 3.7.3
  Pipfile.lock
Labels: bot

#66 Fix missing import
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#94 Automatic update of dependency boto3 from 1.8.1 to 1.8.2
  Pipfile.lock
Labels: bot

#93 Automatic update of dependency pytest-timeout from 1.3.1 to 1.3.2
  Pipfile.lock
Labels: bot

#65 Store information about Python vulnerabilities
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/M

#95 some pytest fixed wrt the prefix
  tests/test_analyses.py
  tests/test_ceph.py
  tests/test_solvers.py
Labels: approved, size/XS

#99 Release of version 0.5.1
  thoth/storages/__init__.py
Labels: bot, size/XS

#100 Automatic update of dependency thoth-common from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: bot

#101 Automatic update of dependency boto3 from 1.8.2 to 1.8.3
  Pipfile.lock
Labels: bot

#104 Automatic update of dependency thoth-common from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: bot

#108 Release of version 0.5.2
  thoth/storages/__init__.py
Labels: bot, size/XS

#110 Release of version 0.5.3
  thoth/storages/__init__.py
Labels: bot, size/XS

#111 Release of version 0.5.4
  thoth/storages/__init__.py
Labels: bot, size/XS

#112 Release of version 0.5.5
  thoth/storages/__init__.py
Labels: bot, size/XS
