Repository thoth-station/storages, pull requests merged in 2018-09, with the labels that each got.

#114 Revert "Release of version 0.5.6"
  thoth/storages/__init__.py
Labels: size/XS

#116 Release of version 0.5.2
  thoth/storages/__init__.py
Labels: bot, size/XS

#106 Sync debian packages to the graph database
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: approved, size/L

#121 Automatic update of dependency thoth-common from 0.2.4 to 0.3.1
  Pipfile.lock
Labels: bot

#123 Automatic update of dependency pytest-cov from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot

#120 Automatic update of dependency boto3 from 1.8.3 to 1.9.9
  Pipfile.lock
Labels: bot

#122 Automatic update of dependency pytest from 3.7.3 to 3.8.1
  Pipfile.lock
Labels: bot

#125 Introduce check whether the given Python package exists
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#126 Automatic update of dependency boto3 from 1.9.9 to 1.9.10
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency thoth-common from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: bot

#131 Specify Python index from which the package came from
  thoth/storages/graph/models.py
Labels: approved, size/XS

#133 Automatic update of dependency thoth-common from 0.3.2 to 0.3.5
  Pipfile.lock
Labels: bot

#135 Automatic update of dependency boto3 from 1.9.11 to 1.9.14
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency thoth-common from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot
