Repository thoth-station/storages, pull requests merged in 2018-10, with the labels that each got.

#141 Automatic update of dependency boto3 from 1.9.14 to 1.9.15
  Pipfile.lock
Labels: bot

#138 Update README file
  README.rst
Labels: approved, size/S

#143 Automatic update of dependency boto3 from 1.9.15 to 1.9.16
  Pipfile.lock
Labels: bot

#142 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#134 Introduce query for gathering dependencies
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#119 Introduce observation models and adapter
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/__init__.py
  thoth/storages/graph/models.py
  thoth/storages/observations.py
Labels: approved, size/M

#155 Automatic update of dependency boto3 from 1.9.19 to 1.9.21
  Pipfile.lock
Labels: bot

#154 using envvar injected by OpenShift to discover janusgraph service
  thoth/storages/graph/janusgraph.py
Labels: size/S

#158 Release of version 0.5.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#160 Automatic update of dependency boto3 from 1.9.21 to 1.9.22
  Pipfile.lock
Labels: bot

#156 Automatic update of dependency thoth-common from 0.3.6 to 0.3.11
  Pipfile.lock
Labels: approved, bot

#164 Automatic update of dependency boto3 from 1.9.22 to 1.9.23
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency boto3 from 1.9.23 to 1.9.24
  Pipfile.lock
Labels: bot

#169 Add timestamp to the result schema
  thoth/storages/result_schema.py
Labels: approved, size/XS

#173 Automatic update of dependency pytest from 3.8.2 to 3.9.1
  Pipfile.lock
Labels: bot

#174 Automatic update of dependency boto3 from 1.9.24 to 1.9.25
  Pipfile.lock
Labels: bot

#175 Automatic update of dependency boto3 from 1.9.25 to 1.9.26
  Pipfile.lock
Labels: bot

#176 Automatic update of dependency requests from 2.19.1 to 2.20.0
  Pipfile.lock
Labels: bot

#177 Automatic update of dependency boto3 from 1.9.26 to 1.9.27
  Pipfile.lock
Labels: bot

#178 Automatic update of dependency boto3 from 1.9.27 to 1.9.28
  Pipfile.lock
Labels: bot

#179 Automatic update of dependency thoth-common from 0.3.11 to 0.3.12
  Pipfile.lock
Labels: bot

#183 Release of version 0.6.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#184 Automatic update of dependency boto3 from 1.9.28 to 1.9.29
  Pipfile.lock
Labels: bot

#185 Automatic update of dependency pytest from 3.9.1 to 3.9.2
  Pipfile.lock
Labels: bot

#187 Automatic update of dependency boto3 from 1.9.29 to 1.9.30
  Pipfile.lock
Labels: bot

#189 Automatic update of dependency boto3 from 1.9.30 to 1.9.32
  Pipfile.lock
Labels: bot

#192 Automatic update of dependency thoth-common from 0.3.12 to 0.3.13
  Pipfile.lock
Labels: bot

#172 Fix CI
  tests/base.py
  tests/data/schema/metadata_ok_1.json
  tests/data/schema/result_ok_analyzer_1.json
  tests/data/schema/result_ok_solver_1.json
  tests/graph/test_cache.py
  tests/graph/test_janusgraph.py
  tests/test_analyses.py
  tests/test_buildlogs.py
  tests/test_ceph.py
  tests/test_result_base.py
  tests/test_solvers.py
  thoth/storages/buildlogs.py
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models_base.py
  thoth/storages/graph/utils.py
  thoth/storages/result_base.py
Labels: approved, size/M, size/S

#194 Automatic update of dependency thoth-common from 0.3.13 to 0.3.14
  Pipfile.lock
Labels: bot

#196 Automatic update of dependency thoth-common from 0.3.14 to 0.3.15
  Pipfile.lock
Labels: bot

#197 Use job id as document id instead of pod id
  thoth/storages/result_base.py
Labels: approved, size/XS

#200 Release of version 0.7.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#203 Release of version 0.7.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#202 Automatic update of dependency thoth-common from 0.3.15 to 0.3.16
  Pipfile.lock
Labels: bot

#199 Automatic update of dependency boto3 from 1.9.33 to 1.9.34
  Pipfile.lock
Labels: bot

#205 Introduce unsolvable flag
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: approved, size/M
