Repository thoth-station/storages, pull requests merged in 2018-07, with the labels that each got.

#40 Fix/coala 120
  .coafile
  CHANGELOG.md
  thoth/storages/__init__.py
  thoth/storages/buildlogs.py
  thoth/storages/ceph.py
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_base.py
  thoth/storages/graph/utils.py
  thoth/storages/result_base.py
Labels: approved, size/L

#45 removing pydocstyle
  .coafile
  Pipfile
  Pipfile.lock
  tests/test_buildlogs.py
  tests/test_ceph.py
Labels: approved

#46 Automatic update of dependency boto3 from 1.7.51 to 1.7.52
  Pipfile.lock
Labels: bot

#47 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#48 Automatic update of dependency cython from 0.28.3 to 0.28.4
  Pipfile.lock
Labels: bot

#49 Automatic update of dependency boto3 from 1.7.52 to 1.7.54
  Pipfile.lock
Labels: bot

#52 Automatic update of dependency boto3 from 1.7.54 to 1.7.55
  Pipfile.lock
Labels: bot

#53 Automatic update of dependency boto3 from 1.7.54 to 1.7.55
  Pipfile.lock
Labels: bot

#54 Automatic update of dependency boto3 from 1.7.54 to 1.7.55
  Pipfile.lock
Labels: bot

#55 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#56 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#57 Automatic update of dependency boto3 from 1.7.55 to 1.7.56
  Pipfile.lock
Labels: bot

#59 Make slash after prefix explicit
  thoth/storages/ceph.py
Labels: approved

#60 Fix key addressing
  thoth/storages/ceph.py
Labels: approved

#63 Update requirements.txt respecting requirements in Pipfile
  requirements.txt
Labels: bot, size/XS
