Repository thoth-station/storages, pull requests merged in 2018-11, with the labels that each got.

#211 Automatic update of dependency boto3 from 1.9.35 to 1.9.36
  Pipfile.lock
Labels: bot

#144 Introduce transitive dependencies gathering method
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#215 Automatic update of dependency boto3 from 1.9.36 to 1.9.37
  Pipfile.lock
Labels: bot

#214 Normalize names of packages that are inserted into graph database
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#213 Introduce methods for checking unsolvable and unparsed packages
  thoth/storages/graph/janusgraph.py
Labels: approved, size/M

#218 Keep schema up2date with recent schema changes
  .gitignore
  docs/schema.dia
  docs/schema.png
Labels: approved, size/XS

#219 Automatic update of dependency pytest from 3.9.3 to 3.10.0
  Pipfile.lock
Labels: bot

#212 Introduce unparsed flag
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#216 Hostname is not equal to document id
  thoth/storages/graph/janusgraph.py
Labels: approved, size/L, size/M

#223 Automatic update of dependency thoth-common from 0.3.16 to 0.4.0
  Pipfile.lock
Labels: bot

#224 Automatic update of dependency moto from 1.3.6 to 1.3.7
  Pipfile.lock
Labels: bot

#225 Fix query to retrieve all package versions
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#220 Fix CI failures
  .coafile
  tests/data/result/analyzer/fridex-thoth-package-extract-tensorflow-serving-s2i
  tests/data/result/solver/fridex-thoth-solver-fc26-thoth-solver-fc26
  tests/test_result_base.py
  tests/test_solvers.py
Labels: approved, size/M, size/S, size/XS

#229 Automatic update of dependency boto3 from 1.9.37 to 1.9.38
  Pipfile.lock
Labels: bot

#230 Automatic update of dependency boto3 from 1.9.38 to 1.9.39
  Pipfile.lock
Labels: bot

#233 Release of version 0.7.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#235 Fix unparseable solver result sync
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#237 Release of version 0.7.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#238 Automatic update of dependency boto3 from 1.9.39 to 1.9.40
  Pipfile.lock
Labels: bot

#232 Correctly handle decorator wrappers
  thoth/storages/graph/utils.py
Labels: approved, size/XS

#239 Methods suitable for metrics
  thoth/storages/graph/janusgraph.py
  thoth/storages/result_base.py
Labels: approved, size/M

#240 Fix queries to janusgraph - aggregate by document ids
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#217 Use common date utilities for creating datetime from timestamp
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#242 Release of version 0.7.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#243 Fix indentation error
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#245 Release of version 0.7.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#248 Extend quieries to janusgraph
  thoth/storages/graph/janusgraph.py
Labels: approved, size/M

#251 Automatic update of dependency requests from 2.20.0 to 2.20.1
  Pipfile.lock
Labels: bot

#252 Automatic update of dependency boto3 from 1.9.40 to 1.9.41
  Pipfile.lock
Labels: bot

#256 Automatic update of dependency pytest from 3.10.0 to 3.10.1
  Pipfile.lock
Labels: bot

#258 Automatic update of dependency boto3 from 1.9.42 to 1.9.43
  Pipfile.lock
Labels: bot

#260 Add a query to check for solved packages
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#263 Automatic update of dependency boto3 from 1.9.43 to 1.9.44
  Pipfile.lock
Labels: bot

#265 Automatic update of dependency pytest from 3.10.1 to 4.0.0
  Pipfile.lock
Labels: bot

#266 Automatic update of dependency boto3 from 1.9.44 to 1.9.45
  Pipfile.lock
Labels: bot

#268 Release of version 0.8.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#271 Automatic update of dependency thoth-common from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#272 Automatic update of dependency boto3 from 1.9.45 to 1.9.46
  Pipfile.lock
Labels: bot

#273 Automatic update of dependency thoth-common from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#274 Automatic update of dependency pytest-timeout from 1.3.2 to 1.3.3
  Pipfile.lock
Labels: bot

#275 Automatic update of dependency boto3 from 1.9.46 to 1.9.47
  Pipfile.lock
Labels: bot

#277 Automatic update of dependency thoth-common from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#281 Automatic update of dependency thoth-common from 0.4.3 to 0.4.4
  Pipfile.lock
Labels: bot

#284 Automatic update of dependency boto3 from 1.9.47 to 1.9.48
  Pipfile.lock
Labels: bot

#288 Fix pytest4 warning
  tests/test_result_base.py
Labels: approved, size/XS

#170 using thoth-pytest job
  .coafile
  .zuul.yaml
  pyproject.toml
  thoth/storages/graph/models_base.py
  thoth/storages/result_base.py
Labels: approved, size/M, size/S, size/XS

#290 Introduce methods for checking documents based on id
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#297 Do not use schema for inspections
  thoth/storages/inspections.py
  thoth/storages/result_base.py
Labels: size/S

#296 Fix CI
  thoth/storages/__init__.py
Labels: size/XS

#300 Automatic update of dependency boto3 from 1.9.48 to 1.9.49
  Pipfile.lock
Labels: bot

#291 Introduce buildtime environment model
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
  thoth/storages/inspections.py
  thoth/storages/result_base.py
Labels: approved, size/L, size/M, size/S

#313 Automatic update of dependency boto3 from 1.9.49 to 1.9.50
  Pipfile.lock
Labels: bot

#318 Introduce method for registering Python package indexes
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/S

#317 Introduce query for computing performance index
  thoth/storages/graph/janusgraph.py
Labels: size/M

#322 Add method for retrieving Python package index URLs
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#326 Introduce graceful flag for inspection syncs
  thoth/storages/sync.py
Labels: size/XS

#328 Log about Amun results gathering
  thoth/storages/sync.py
Labels: size/XS

#327 Fix key error if hardware was not provided on Amun
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#329 Improve handling of performance index
  thoth/storages/graph/janusgraph.py
Labels: size/S

#330 Report which inspection id is being synced
  thoth/storages/sync.py
Labels: size/XS

#345 Automatic update of dependency pytest from 4.0.0 to 4.0.1
  Pipfile.lock
Labels: bot

#348 Automatic update of dependency cython from 0.29 to 0.29.1
  Pipfile.lock
Labels: bot

#335 Add long description for PyPI
  setup.py
Labels: approved, size/XS

#359 Automatic update of dependency boto3 from 1.9.50 to 1.9.51
  Pipfile.lock
Labels: bot

#361 Create digest entries in the graph database for python packages
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/M, size/S

#370 Introduce query for gathering sha256 hashes
  thoth/storages/graph/janusgraph.py
Labels: size/S

#378 Release of version 0.9.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#381 Include index url in the releases listing
  thoth/storages/graph/janusgraph.py
Labels: size/S

#387 Fixes for CI
  .coafile
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/S

#379 Automatic update of dependency amun from 0.1.3 to 0.2.0
  Pipfile.lock
Labels: bot

#385 Automatic update of dependency boto3 from 1.9.51 to 1.9.55
  Pipfile.lock
Labels: bot

#386 Consider index when retrieving transitive dependencies
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS
