Repository thoth-station/storages, pull requests merged in 2018-06, with the labels that each got.

#31 Rename THOTH_CEPH_HOST to THOTH_S3_ENDPOINT_URL
  tests/test_ceph.py
  thoth/storages/ceph.py
Labels: approved, lgtm, size/XS

#32 Use prefix with slash for Ceph
  thoth/storages/ceph.py
Labels: approved, size/XS

#37 Fix variable name
  tests/test_ceph.py
  thoth/storages/ceph.py
Labels: size/XS

#38 Version 0.0.31
  thoth/storages/__init__.py
Labels: size/XS

#39 Version 0.0.32
  thoth/storages/__init__.py
Labels: size/XS
