Repository thoth-station/storages, pull requests merged in 2019-02, with the labels that each got.

#477 Distinguish different software stacks by their types
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/M

#480 Update year in sources
  tests/__init__.py
  tests/base.py
  tests/graph/__init__.py
  tests/graph/test_cache.py
  tests/graph/test_janusgraph.py
  tests/test_analyses.py
  tests/test_buildlogs.py
  tests/test_ceph.py
  tests/test_result_base.py
  tests/test_result_schema.py
  tests/test_solvers.py
  tests/utils.py
  thoth/storages/__init__.py
  thoth/storages/advisers.py
  thoth/storages/advisers_cache.py
  thoth/storages/analyses.py
  thoth/storages/analyses_by_digest.py
  thoth/storages/analyses_cache.py
  thoth/storages/base.py
  thoth/storages/buildlogs.py
  thoth/storages/ceph.py
  thoth/storages/ceph_cache.py
  thoth/storages/dependency_monkey_reports.py
  thoth/storages/exceptions.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_base.py
  thoth/storages/graph/utils.py
  thoth/storages/inspections.py
  thoth/storages/observations.py
  thoth/storages/provenance.py
  thoth/storages/provenance_cache.py
  thoth/storages/result_base.py
  thoth/storages/result_schema.py
  thoth/storages/solvers.py
  thoth/storages/sync.py
Labels: size/M

#485 Fix wrong import
  thoth/storages/graph/__init__.py
Labels: size/XS

#492 Adjust CVE query to include version range
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#497 Add platform specific features to the transitive query
  thoth/storages/graph/janusgraph.py
Labels: size/M

#496 Automatic update of dependency cython from 0.29.3 to 0.29.5
  Pipfile.lock
Labels: bot

#473 Automatic update of dependency pytest from 4.1.1 to 4.2.0
  Pipfile.lock
Labels: bot

#495 Automatic update of dependency boto3 from 1.9.84 to 1.9.91
  Pipfile.lock
Labels: bot

#499 Consider hardware with no None values
  thoth/storages/graph/janusgraph.py
Labels: size/M

#500 Let callee preserve None values
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#501 Respect runtime environment in queries for direct dependencies
  thoth/storages/graph/janusgraph.py
Labels: size/S

#510 If adviser analysis was not succesfull no lockfile is provided
  thoth/storages/graph/janusgraph.py
Labels: size/S

#512 Release of version 0.9.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#521 Add python version and cuda version to graph schema
  .coafile
Labels: size/XS

#524 Update README with the most recent information about schema generation
  README.rst
Labels: size/S

#525 Adjust query to return unsolved packages for the given solver
  thoth/storages/graph/janusgraph.py
Labels: size/S

#531 Add CVE name when querying for CVEs
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#532 Update schema in docs
  docs/schema.dia
  docs/schema.png
Labels: size/XS

#534 Be consistent with property naming
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/models.py
Labels: size/XS

#535 Fix path to origin value of adviser and provenance-checker resutls
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#539 Add missing export from thoth.storages module
  thoth/storages/__init__.py
Labels: size/XS

#541 Fix solver name handling
  thoth/storages/graph/janusgraph.py
  thoth/storages/solvers.py
Labels: size/S

#542 This repo requires Python 3.6
  Pipfile
  Pipfile.lock
Labels: size/L, size/XS

#536 adopted zuul's new trigger-build job
  .coafile
  .zuul.yaml
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: approved, size/L, size/XS

#549 Remove duplicit definition
  thoth/storages/graph/models.py
Labels: size/XS
