Repository thoth-station/storages, pull requests merged in 2019-04, with the labels that each got.

#574 New Edge between PythonPackageVersion and PythonPackageIndex #556
  thoth/storages/graph/models.py
Labels: approved, size/XS

#577 Updated schema for missing/wrong properties, added new index
  thoth/storages/graph/models.py
Labels: size/XS

#578 update schema file with new edge "has_index"
  docs/schema.dia
  docs/schema.png
Labels: approved, size/XS

#583 Fix sync of edge sync - source and target should not be part of sync
  thoth/storages/graph/models_base.py
Labels: size/XS

#585 Improve schema handling
  create_schema.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/L

#587 Implement get_python_package_index_urls for Dgraph
  thoth/storages/graph/dgraph.py
Labels: size/S

#588 Minor code fixes
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models_base.py
Labels: size/M

#582 Introduce solver_document_id_exist method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: size/S

#589 Fix facets syntax when syncing edges dictionaries
  thoth/storages/graph/models_base.py
Labels: size/XS

#586 Implemented get_analysis_metadata method for Dgraph
  Pipfile
  requirements.txt
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#579 New functions in janusgraph for metrics exporter
  thoth/storages/graph/janusgraph.py
Labels: approved, size/L, size/M

#592 Implemented get_all_python_packages_count method for Dgraph
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/S

#581 Add register_python_package_index to Dgraph implementation
  thoth/storages/graph/dgraph.py
Labels: size/S

#594 Release of version 0.10.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#590 Schema proposal for Dgraph
  Pipfile
  Pipfile.lock
  create_schema.py
  docs/schema.dia
  docs/schema.png
  requirements.txt
  setup.py
  thoth/storages/dependency_monkey_reports.py
  thoth/storages/exceptions.py
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_base.py
  thoth/storages/graph/schema.rdf
  thoth/storages/sync.py
Labels: size/L, size/XL, size/XS, size/XXL

#597 Fix syncing dependencies found in solver documents
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#599 Remove checks which are already present in _create_python_package_record
  thoth/storages/graph/dgraph.py
Labels: approved, size/M

#596 Add missing annotations to models
  thoth/storages/graph/models.py
Labels: approved, size/XS

#595 Sync also digests when syncing solver documents
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#600 Dgraph fix client connection for query
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#601 Retrieve read-only transaction for query operations
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#584 Implement runtime_environment_listing for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#602 Fix handling target UID for vertexes
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#604 Implement query for retrieving solver error count
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/M

#606 Implement query for retrieving image analysis count
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#603 User software stack can have adviser or provenance-checker document id
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/S

#605 Fix query to retrieve solver count
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#607 Fix query for checking solver document presence
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#609 Implemment logic for checking if adviser run is present in db
  thoth/storages/graph/dgraph.py
Labels: approved, size/M, size/S

#608 Implement logic for querying for DependencyMonkey document presence
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#610 Add query for checking presence of inspection runs
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#611 Add query for checking provenance checker document id presence
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#614 Implement query for retrieving artifact hashes from database
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#612 Implement method for gathering CVEs for Python packages
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#615 Remove unused imports in dgraph.py implementation
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#616 Add Francesco to module authors
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#617 Fix get_analysis_metadata function, sync_functions, models and graph …
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/S

#628 Implemented solver_records_exist method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#627 Implemented analysis_records_exist method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#626 Implemented get_python_packages method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#625 Implemented get_python_packages_for_index method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#623 Implemented python_package_version_exists method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#622 Implemented python_package_exists method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#624 Implemented get_all_python_package_version_hashes_sha256 method for D…
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#621 Implemented retrieve_unparseable_pypi_packages method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#620 Implemented retrieve_unsolvable_pypi_packages method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: size/S

#619 Implemented retrieve_solved_pypi_packages method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#613 Implemented get_all_versions_python_package method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/M

#633 Remove obsolete queries
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#632 Implement get_python_package_tuples for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/M

#629 Add missing provenance checker name
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/XS

#635 Implemented retrieve_dependent_packages method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#636 Implemented retrieve_unsolved_pypi_packages method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#631 Fix python_sync_analysis
  thoth/storages/graph/dgraph.py
Labels: approved, size/L, size/M, size/XS

#634 Implement method for gathering average performance
  thoth/storages/graph/dgraph.py
Labels: approved, size/L

#642 Implemented runtime_environment_analyses_listing method for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#646 Return None if no entity was found for in query_one
  thoth/storages/graph/models_base.py
Labels: size/XS

#647 Fix coala complains
  .coafile
  thoth/storages/graph/dgraph.py
Labels: size/XS

#643 Automatic update of dependency boto3 from 1.9.130 to 1.9.134
  Pipfile.lock
Labels: bot

#644 Automatic update of dependency pydgraph from 1.0.3 to 1.1
  Pipfile.lock
Labels: bot

#645 Automatic update of dependency moto from 1.3.7 to 1.3.8
  Pipfile.lock
Labels: bot

#649 Release of version 0.11.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#650 Automatic update of dependency boto3 from 1.9.134 to 1.9.135
  Pipfile.lock
Labels: bot

#651 Remove unused method
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#652 Normalize Python package names before inserting them into database
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#654 Automatic update of dependency boto3 from 1.9.135 to 1.9.136
  Pipfile.lock
Labels: bot

#655 Automatic update of dependency boto3 from 1.9.136 to 1.9.137
  Pipfile.lock
Labels: bot

#656 Automatic update of dependency pydgraph from 1.1 to 1.1.1
  Pipfile.lock
Labels: bot

#657 Automatic update of dependency boto3 from 1.9.137 to 1.9.138
  Pipfile.lock
Labels: bot

#658 Automatic update of dependency boto3 from 1.9.138 to 1.9.139
  Pipfile.lock
Labels: bot
