Repository thoth-station/storages, pull requests merged in 2019-09, with the labels that each got.

#917 Automatic update of dependency boto3 from 1.9.220 to 1.9.221
  Pipfile.lock
Labels: bot

#918 Automatic update of dependency boto3 from 1.9.221 to 1.9.222
  Pipfile.lock
Labels: bot

#905 Remove index key in syncing
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#906 Add error flag to package analyzer run
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#907 Sync package analyzer error
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/XS

#919 Automatic update of dependency boto3 from 1.9.222 to 1.9.223
  Pipfile.lock
Labels: bot

#921 Automatic update of dependency pydgraph from 1.2.0 to 2.0.1
  Pipfile.lock
Labels: bot

#922 Automatic update of dependency boto3 from 1.9.223 to 1.9.224
  Pipfile.lock
Labels: bot

#924 Remove old schema files
  .gitignore
  README.rst
  docs/schema.dia
  docs/schema.png
  thoth/storages/cli.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph_cache.py
Labels: approved, size/L, size/M, size/S

#926 Postgresql index enabled
  thoth/storages/graph/postgres.py
Labels: approved, size/S, size/XS

#927 Fix property name
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#928 Automatic update of dependency boto3 from 1.9.224 to 1.9.225
  Pipfile.lock
Labels: bot

#929 Implement logic for syncing package-extract results
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#930 Implement logic for syncing provenance checker results
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#931 Postgresql sync adviser result
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#935 Move cache specific function to cache implementation
  thoth/storages/graph/cache.py
  thoth/storages/graph/models_base.py
Labels: approved, size/M

#936 Unify Python package version handling in PostgreSQL
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#937 Postgresql stack handling
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#888 Store symbols
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
Labels: approved, size/M, size/S

#938 WIP: Introduce logic for syncing dependency-monkey documents
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#939 Substitute from_properties with get_or_create in performance models
  thoth/storages/graph/models_performance.py
Labels: approved, size/XS

#941 Fix invalid foreign key error on schema creation
  thoth/storages/graph/models.py
Labels: approved, size/XS

#943 Minor fixes to make dependency monkey syncs work properly
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#946 Unify environment type handling
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#948 Make methods which create data without starting transaction private
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#952 Count number of performance indicators based on framework
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#950 Implement method for listing analyses
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#951 Introduce method for counting performance indicator entries
  thoth/storages/graph/postgres.py
Labels: approved, size/S, size/XS

#954 Automatic update of dependency boto3 from 1.9.225 to 1.9.226
  Pipfile.lock
Labels: bot

#955 Adjust query for retrieving performance indicators
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#949 Implement method for getting analysis metadata
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#945 Sync system symbols detected by a package-extract
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#956 Minor changes in PostgreSQL implementation
  tests/graph/test_cache.py
  thoth/storages/cli.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#957 Remove debug warnings accidentally committed
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#958 PostgreSQL sync package analyzer results
  .coafile
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#940 WIP: Logic to sync inspection results
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#961 Automatic update of dependency boto3 from 1.9.226 to 1.9.227
  Pipfile.lock
Labels: bot

#960 Disable cache inserts by default as they are expensive
  README.rst
  tests/graph/test_cache.py
  thoth/storages/graph/cache.py
Labels: approved, size/S

#962 Drop performance related query
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#965 Use more generic env variable names
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#966 Automatic update of dependency boto3 from 1.9.228 to 1.9.229
  Pipfile.lock
Labels: bot

#967 Switch from Dgraph to PostgreSQL
  .coafile
  .gitignore
  Pipfile
  Pipfile.lock
  README.rst
  create_schema.py
  docker-compose.yaml
  docs/schema.dia
  docs/schema.png
  requirements.txt
  setup.py
  tests/graph/_test_cache.py
  tests/graph/test_cache.py
  thoth-storages
  thoth/storages/__init__.py
  thoth/storages/cli.py
  thoth/storages/graph/__init__.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_base.py
  thoth/storages/graph/models_cache.py
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph/schema.rdf
  thoth/storages/graph/sql_base.py
  thoth/storages/graph_cache.py
  thoth/storages/sync.py
Labels: approved, size/XXL

#968 Add missing import
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#969 Add missing software stack relation to inspections
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#970 Remove unused imports
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#975 Remove accidentally committed file
  tests/graph/_test_cache.py
Labels: approved, size/M

#974 Provide method for disabling and enabling Python package index
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#973 Automatic update of dependency pydgraph from 1.2.0 to 2.0.2
  Pipfile.lock
Labels: bot

#972 Automatic update of dependency boto3 from 1.9.222 to 1.9.229
  Pipfile.lock
Labels: bot

#971 Log statistics of graph cache and memory cache if requested so
  README.rst
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#977 Release of version 0.19.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/L

#978 Automatic update of dependency thoth-python from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#979 Use more generic env variable names
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#981 Release of version 0.19.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#982 Implemented CASCADE on delete for Foreign Keys
  thoth/storages/graph/models.py
Labels: approved, size/L

#984 Fix documentation for performance indicators
  README.rst
Labels: approved, size/XS

#985 Update inspection sync
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#986 Release of version 0.19.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#987 Disable connection pooling
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#989 Release of version 0.19.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#990 Automatic update of dependency boto3 from 1.9.229 to 1.9.230
  Pipfile.lock
Labels: bot

#992 Count and limit for advises can be nullable
  thoth/storages/graph/models.py
Labels: approved, size/XS

#991 Increase advisory message for CVEs
  thoth/storages/graph/models.py
Labels: approved, size/XS

#994 Release of version 0.19.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#995 Adjust signature of method for retrieving unsolved python packages
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#997 Fix unsolved Python packages query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#998 New class methods for InspectionStore
  thoth/storages/inspections.py
Labels: approved, size/S

#999 Randomize retrieval of unsolved Python packages
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1000 Adjust logged message to inform about concurrent writes
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#1001 Document how to dump and restore database in the running cluster
  README.rst
Labels: approved, size/S

#1003 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#1004 Release of version 0.19.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1005 Automatic update of dependency boto3 from 1.9.230 to 1.9.231
  Pipfile.lock
Labels: bot

#1006 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#1009 Start using Alembic for database migrations
  .coafile
  Pipfile
  Pipfile.lock
  README.rst
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/9168881dd125_initial_schema.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph/sql_base.py
Labels: approved, size/XXL

#1008 Add missing method used to register new packages in package releases
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1011 Fix small typo
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1012 Automatic update of dependency boto3 from 1.9.231 to 1.9.232
  Pipfile.lock
Labels: bot

#1010 Make sure devs update to most recent version before generating new versions
  README.rst
Labels: approved, size/XS

#1014 Normalize Python package versions before each insert or query
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1015 Automatic update of dependency alembic from 1.1.0 to 1.2.0
  Pipfile.lock
Labels: bot

#1016 Automatic update of dependency boto3 from 1.9.232 to 1.9.233
  Pipfile.lock
Labels: bot

#1017 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#1019 Add missing migrations to requirements.txt file
  requirements.txt
Labels: size/XS

#1020 Release of version 0.19.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1022 Distribute alembic migrations with thoth-storages
  .coafile
  alembic
  alembic.ini
  alembic/README
  setup.py
  thoth/storages/data/alembic.ini
  thoth/storages/data/alembic/env.py
  thoth/storages/data/alembic/script.py.mako
  thoth/storages/data/alembic/versions/9168881dd125_initial_schema.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1024 Automatic update of dependency thoth-python from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#1026 Make solver name optional when retrieving unsolved packages
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1027 Automatic update of dependency boto3 from 1.9.233 to 1.9.234
  Pipfile.lock
Labels: bot

#1032 Fix path to alembic versions - it has changed recently
  README.rst
Labels: approved, size/XS

#1035 Automatic update of dependency boto3 from 1.9.234 to 1.9.235
  Pipfile.lock
Labels: bot

#1036 Automatic update of dependency alembic from 1.2.0 to 1.2.1
  Pipfile.lock
Labels: bot

#1037 State graphviz package as a dependency when generating schema images
  README.rst
Labels: approved, size/S

#1038 Log what is being synced during graph syncs
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1039 WIP: Use podman-compose
  README.rst
  docker-compose.yaml
Labels: approved, size/S

#1040 Automatic update of dependency boto3 from 1.9.235 to 1.9.236
  Pipfile.lock
Labels: bot

#1041 Show an example run how to create a local PostgreSQL instance
  README.rst
Labels: approved, size/S

#1042 Update queries
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1045 Automatic update of dependency boto3 from 1.9.236 to 1.9.237
  Pipfile.lock
Labels: bot

#1043 New and updated queries
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1044 New query: count software stacks per type
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1047 Release of version 0.19.8
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1054 Automatic update of dependency boto3 from 1.9.237 to 1.9.238
  Pipfile.lock
Labels: bot

#1055 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#1053 Add duration to the result schema
  tests/data/schema/metadata_ok_1.json
  tests/data/schema/result_ok_analyzer_1.json
  tests/data/schema/result_ok_solver_1.json
  thoth/storages/result_schema.py
Labels: approved, human_intervention_required, size/XS

#1057 Release of version 0.19.9
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1050 New queries for python packages
  thoth/storages/graph/postgres.py
Labels: approved, size/M, size/S

#1058 Automatic update of dependency boto3 from 1.9.238 to 1.9.239
  Pipfile.lock
Labels: bot
