Repository thoth-station/storages, pull requests merged in 2019-07, with the labels that each got.

#776 Automatic update of dependency moto from 1.3.8 to 1.3.9
  Pipfile.lock
Labels: bot

#777 alphabetically order the files
  thoth/storages/__init__.py
Labels: approved, size/XS

#780 Automatic update of dependency boto3 from 1.9.180 to 1.9.181
  Pipfile.lock
Labels: bot

#781 Automatic update of dependency boto3 from 1.9.181 to 1.9.182
  Pipfile.lock
Labels: bot

#782 Automatic update of dependency boto3 from 1.9.182 to 1.9.183
  Pipfile.lock
Labels: bot

#786 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#784 Introduce retry exception on concurrent upsert writes
  thoth/storages/exceptions.py
  thoth/storages/graph/models_base.py
Labels: size/XS

#788 Release of version 0.14.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#778 updated adapters for storing buildlog analysis results and cache
  thoth/storages/__init__.py
  thoth/storages/buildlogs_analyses.py
  thoth/storages/buildlogs_analyses_cache.py
Labels: approved, size/M

#791 Release of version 0.14.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#790 Introduce method for creating Python package version entities
  thoth/storages/graph/dgraph.py
Labels: approved, size/M

#792 Automatic update of dependency boto3 from 1.9.183 to 1.9.184
  Pipfile.lock
Labels: bot

#794 Release of version 0.14.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#795 Automatic update of dependency boto3 from 1.9.184 to 1.9.185
  Pipfile.lock
Labels: bot

#785 Require non-null `index_url` and `package_name`
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#796 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#797 Automatic update of dependency boto3 from 1.9.185 to 1.9.186
  Pipfile.lock
Labels: bot

#799 Release of version 0.14.7
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#802 Parametrize retrieval of unsolvable packages for the given solver
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#801 Update README to show how to connect to the graph database from code
  README.rst
Labels: size/S

#803 Change log error to warning
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#804 Document schema hadnling in a living deployment
  README.rst
Labels: approved, size/S

#806 Release of version 0.14.8
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#779 sync_package_analysis_documents
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, do-not-merge/work-in-progress, size/M

#807 Add PythonFileDigest to schema documentation
  docs/schema.dia
  docs/schema.png
Labels: approved, size/XS

#808 Introduce delete operation on top of models
  thoth/storages/exceptions.py
  thoth/storages/graph/models_base.py
Labels: approved, size/S

#810 Add standard project template and code owners
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#811 Fix vertex cache handling
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#812 Unify schema for creating performance indicators and their handling
  README.rst
  thoth/storages/exceptions.py
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/performance.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/L

#813 Update schema image respecting recent changes in PiMatmul
  docs/schema.dia
  docs/schema.png
Labels: approved, size/XS

#815 Sync information about operating system captured in package-extract
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
Labels: approved, size/S, size/XS

#816 Update schema based on updates to performance indicators
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/performance.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/M

#817 Fix typo in matrix
  thoth/storages/graph/performance.py
Labels: approved, size/XS

#820 Release of version 0.15.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#819 Enable logging of graph database queries for debugging
  README.rst
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#818 Fix handling of query filter
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#822 Add checks for inspection document syncing
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#825 Fix default value to environment variable
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#824 Fix handling of missing usage in the inspection documents when syncing
  thoth/storages/graph/performance.py
Labels: approved, size/M

#827 Release of version 0.15.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#829 Inspection specification is a dictionary
  thoth/storages/inspection_schema.py
Labels: approved, size/XS

#831 Queries are concurrent, not parallel
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#830 Decrease transitive query depth to address serialization issues
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#833 Release of version 0.15.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#835 Query for package versions without error by default
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#837 Quote user input parts of the query in error message produced
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#840 Modified Inspection schema
  thoth/storages/inspection_schema.py
Labels: approved, size/XS

#839 Updated schema for PIConv
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/performance.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/M

#841 Corrected voluptuous requirements for inspection schema
  thoth/storages/inspection_schema.py
Labels: approved, size/M

#834 sync package analyzer results
  thoth/storages/__init__.py
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
  thoth/storages/sync.py
Labels: approved, size/L

#843 Update schema to include package analyzer
  docs/schema.dia
  docs/schema.png
Labels: approved, size/XS

#845 Release of version 0.16.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#848 Fix handling of pytest arguments in setup.py
  setup.py
Labels: approved, size/S

#838 Optimize retrieval of transitive queries
  docker-compose.yaml
  tests/graph/test_dgraph.py
  thoth/storages/graph/dgraph.py
Labels: approved, size/L, size/M, size/S

#850 Release of version 0.17.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#851 Add PI for Conv1D and Conv2D for tensorflow
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/performance.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/M

#852 New Dgraph function for PI
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#854 Release of version 0.18.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS
