Repository thoth-station/storages, pull requests merged in 2019-05, with the labels that each got.

#659 Automatic update of dependency boto3 from 1.9.139 to 1.9.140
  Pipfile.lock
Labels: bot

#660 Automatic update of dependency boto3 from 1.9.140 to 1.9.141
  Pipfile.lock
Labels: bot

#663 Automatic update of dependency pytest-cov from 2.6.1 to 2.7.1
  Pipfile.lock
Labels: bot

#662 Created missing functions for Dgraph
  thoth/storages/graph/dgraph.py
Labels: approved, size/M

#664 Fix computing edge hashes
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#666 Release of version 0.11.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#667 Automatic update of dependency boto3 from 1.9.141 to 1.9.142
  Pipfile.lock
Labels: bot

#668 Fix missing import causing issues in graph-sync-job
  thoth/storages/__init__.py
Labels: size/XS

#669 Implement back-off for random time in case of concurent upsert writes
  thoth/storages/graph/models_base.py
Labels: size/M

#670 Reorganize Python package creation
  thoth/storages/graph/dgraph.py
Labels: size/S

#672 Minor fix to display correct release in title of docs html
  setup.py
Labels: approved, size/XS

#673 Automatic update of dependency boto3 from 1.9.142 to 1.9.143
  Pipfile.lock
Labels: bot

#674 Automatic update of dependency boto3 from 1.9.143 to 1.9.144
  Pipfile.lock
Labels: bot

#661 Implement query for retrieving information about build-time errors
  thoth/storages/graph/dgraph.py
Labels: size/M, size/S

#675 Introduce mechanism to avoid gRPC issues when serializing large stacks
  thoth/storages/graph/dgraph.py
Labels: size/L

#679 Release of version 0.11.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#680 Automatic update of dependency boto3 from 1.9.144 to 1.9.145
  Pipfile.lock
Labels: bot

#681 Automatic update of dependency pytest from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot

#682 Provide method for buildtime environment listing
  thoth/storages/graph/dgraph.py
Labels: size/M, size/S

#684 Release of version 0.11.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#685 An environment can have no analyses associated
  thoth/storages/graph/dgraph.py
Labels: size/XS

#687 Automatic update of dependency amun from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#688 Automatic update of dependency boto3 from 1.9.145 to 1.9.146
  Pipfile.lock
Labels: bot

#689 Fix normalization issue - normalize only package names
  thoth/storages/graph/dgraph.py
Labels: size/S, size/XS

#691 Release of version 0.11.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#692 Automatic update of dependency pytest from 4.4.2 to 4.5.0
  Pipfile.lock
Labels: bot

#697 Automatic update of dependency boto3 from 1.9.146 to 1.9.147
  Pipfile.lock
Labels: bot

#700 Automatic update of dependency boto3 from 1.9.147 to 1.9.148
  Pipfile.lock
Labels: bot

#701 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#699 Fix number of overall results
  thoth/storages/graph/dgraph.py
Labels: approved

#698 Fix wrong indentation in adviser results sync
  thoth/storages/graph/dgraph.py
Labels: approved

#704 Automatic update of dependency boto3 from 1.9.148 to 1.9.149
  Pipfile.lock
Labels: bot

#703 Check for cyclic dependencies in transitive query
  tests/graph/test_dgraph.py
  tests/graph/test_janusgraph.py
  thoth/storages/graph/dgraph.py
Labels: approved

#705 Update for Dgraph
  README.rst
Labels: approved

#706 Automatic update of dependency boto3 from 1.9.149 to 1.9.150
  Pipfile.lock
Labels: bot

#707 Automatic update of dependency boto3 from 1.9.150 to 1.9.151
  Pipfile.lock
Labels: bot

#702 Update schema and functions with new nodes
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, enhancement

#710 Release of version 0.12.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#711 Release of version 0.13.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#713 Automatic update of dependency boto3 from 1.9.151 to 1.9.152
  Pipfile.lock
Labels: bot

#714 Automatic update of dependency boto3 from 1.9.152 to 1.9.153
  Pipfile.lock
Labels: bot

#716 Provide better exception message on parsing error
  thoth/storages/graph/dgraph.py
Labels: approved

#718 Automatic update of dependency boto3 from 1.9.153 to 1.9.154
  Pipfile.lock
Labels: bot

#719 Automatic update of dependency boto3 from 1.9.154 to 1.9.155
  Pipfile.lock
Labels: bot

#720 Automatic update of dependency boto3 from 1.9.155 to 1.9.156
  Pipfile.lock
Labels: bot

#723 Automatic update of dependency boto3 from 1.9.156 to 1.9.157
  Pipfile.lock
Labels: bot

#717 Ignore changelog file in coala, it's getting too large
  .coafile
Labels: approved, size/XS

#724 Release of version 0.14.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XL

#725 Automatic update of dependency boto3 from 1.9.157 to 1.9.158
  Pipfile.lock
Labels: bot

#726 Automatic update of dependency boto3 from 1.9.158 to 1.9.159
  Pipfile.lock
Labels: bot
