Repository thoth-station/storages, pull requests merged in 2019-11, with the labels that each got.

#1207 Automatic update of dependency sqlalchemy-utils from 0.34.2 to 0.35.0
  Pipfile.lock
Labels: bot

#1209 Automatic update of dependency boto3 from 1.10.7 to 1.10.8
  Pipfile.lock
Labels: bot

#1213 Remove old pydgraph dependency
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/M

#1214 Automatic update of dependency python-dateutil from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#1215 Automatic update of dependency pytest-mypy from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#1212 Randomize retrievals of unanalyzed Python packages
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1216 Relax fatal error on syncing unmatched metadata
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1211 Randomize retrieval of unsolved Python packages
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1198 Introduce enum classes for safe API
  thoth/storages/graph/enums.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L, size/M

#1218 Release of version 0.19.15
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1226 Automatic update of dependency boto3 from 1.10.8 to 1.10.9
  Pipfile.lock
Labels: bot

#1227 Automatic update of dependency python-dateutil from 2.8.1 to 2.8.0
  Pipfile.lock
Labels: bot

#1228 Cache some of the query results for better adviser performance
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1222 Graph database cache has been removed
  README.rst
Labels: approved, size/M

#1225 Fix query to CVE for a given python package version entity
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1220 Sync documents from a local directory if requested
  thoth/storages/sync.py
Labels: approved, size/L

#1232 Automatic update of dependency boto3 from 1.10.9 to 1.10.10
  Pipfile.lock
Labels: bot

#1233 Release of version 0.19.16
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1229 Pick metadata which were computed
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1224 New models for PythonPackage Metadata that have multiple values
  docs/syncs/thoth_sync_solver.graphml
  docs/syncs/thoth_sync_solver.jpg
  thoth/storages/data/alembic/versions/7866a83369ff_created_tables_for_metadata_multi_part_.py
  thoth/storages/exceptions.py
  thoth/storages/graph/enums.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L, size/M, size/XXL

#1199 Correct errors for mypy
  tests/test_result_base.py
  thoth/storages/result_base.py
Labels: approved, size/XS

#1195 Minor changes
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1237 Automatic update of dependency boto3 from 1.10.10 to 1.10.11
  Pipfile.lock
Labels: bot

#1238 Automatic update of dependency boto3 from 1.10.11 to 1.10.12
  Pipfile.lock
Labels: bot

#1239 Standardize sync logic entries
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1240 Adjust sync for inspections
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1242 Release of version 0.19.17
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS, size/XXL

#1243 Automatic update of dependency boto3 from 1.10.12 to 1.10.13
  Pipfile.lock
Labels: bot

#1244 Automatic update of dependency thoth-python from 0.6.5 to 0.7.1
  Pipfile.lock
Labels: bot

#1246 Fix bug in checking for dist key
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1247 Correct attribute for metadata Provides-Extra
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1249 Release of version 0.19.18
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS, size/XXL

#1252 Automatic update of dependency boto3 from 1.10.13 to 1.10.14
  Pipfile.lock
Labels: bot

#1255 Automatic update of dependency boto3 from 1.10.14 to 1.10.15
  Pipfile.lock
Labels: bot

#1256 Automatic update of dependency sqlalchemy from 1.3.10 to 1.3.11
  Pipfile.lock
Labels: bot

#1257 Fix wrong propagation of is_local flag
  thoth/storages/sync.py
Labels: approved, size/XS

#1260 Automatic update of dependency boto3 from 1.10.15 to 1.10.16
  Pipfile.lock
Labels: bot

#1259 Release of version 0.19.19
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS, size/XXL

#1262 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#1263 Automatic update of dependency alembic from 1.3.0 to 1.3.1
  Pipfile.lock
Labels: bot

#1265 Automatic update of dependency boto3 from 1.10.16 to 1.10.17
  Pipfile.lock
Labels: bot, size/M

#1267 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#1269 Automatic update of dependency boto3 from 1.10.17 to 1.10.18
  Pipfile.lock
Labels: bot, size/S

#1270 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/XS

#1268 Optimized/Improved query to retrieve unsolved Python Packages
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1264 State ignoring a role assignment in docs
  README.rst
Labels: approved, size/S

#1266 Fix schema check
  thoth/storages/graph/postgres.py
Labels: approved, human_intervention_required, size/XS

#1273 Adjust output query for metric
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1272 Introduce ping method
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1276 Use default pooling from sqlalchemy
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1275 Release of version 0.19.20
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1277 Dispose engine on connect issues
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1278 Dispose engine on disconnect
  thoth/storages/graph/postgres.py
  thoth/storages/graph/sql_base.py
Labels: approved, size/S

#1280 Automatic update of dependency boto3 from 1.10.18 to 1.10.19
  Pipfile.lock
Labels: bot, size/M

#1281 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#1285 Release of version 0.19.21
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1284 Use same version as in the cluster
  docker-compose.yaml
Labels: approved, size/XS

#1288 Release of version 0.19.22
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1289 Fix warning for migration configuration check
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1287 Correct output of queries
  thoth/storages/graph/models_base.py
Labels: approved, size/XS

#1290 Automatic update of dependency boto3 from 1.10.19 to 1.10.20
  Pipfile.lock
Labels: bot, size/M

#1298 Automatic update of dependency boto3 from 1.10.20 to 1.10.21
  Pipfile.lock
Labels: bot, size/M

#1299 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/XS

#1300 Automatic update of dependency boto3 from 1.10.21 to 1.10.22
  Pipfile.lock
Labels: bot, size/S

#1301 Automatic update of dependency boto3 from 1.10.22 to 1.10.23
  Pipfile.lock
Labels: bot, size/M

#1304 Use context manager for handling sessions
  thoth/storages/graph/postgres.py
  thoth/storages/graph/sql_base.py
Labels: approved, size/XXL

#1306 Release of version 0.19.23
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1309 Automatic update of dependency boto3 from 1.10.23 to 1.10.24
  Pipfile.lock
Labels: bot, size/M

#1310 Automatic update of dependency boto3 from 1.10.24 to 1.10.25
  Pipfile.lock
Labels: bot, size/S

#1313 Add ability to sync documents based on absolute path
  thoth/storages/sync.py
Labels: approved, size/S

#1314 Fix referencing store if is_local is set
  thoth/storages/sync.py
Labels: approved, size/M

#1316 Release of version 0.19.24
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1317 Automatic update of dependency boto3 from 1.10.25 to 1.10.26
  Pipfile.lock
Labels: bot, size/M

#1321 Automatic update of dependency sqlalchemy-stubs from 0.2 to 0.3
  Pipfile.lock
Labels: bot, size/S

#1318 Fix wrong staticmethod
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1297 Introduce sorting type in queries
  thoth/storages/exceptions.py
  thoth/storages/graph/enums.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph/query_result_base.py
Labels: approved, size/M

#1326 Issue warning instead of error for metadata keys not compliant with version 2.1 of core metadata specification.
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1327 Make library thread safe
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1254 added more builds that need to be triggered
  .zuul.yaml
Labels: approved, enhancement, size/M

#1331 Automatic update of dependency boto3 from 1.10.26 to 1.10.27
  Pipfile.lock
Labels: bot, size/M

#1334 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/S

#1333 Use open instead of pathlib to adress PV in-cluster issues
  thoth/storages/sync.py
Labels: approved, size/S

#1336 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#1342 Cache environment marker evaluation result
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1344 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#1329 Optimize queries
  thoth/storages/graph/postgres.py
  thoth/storages/graph/query_result_base.py
Labels: approved, size/XXL

#1328 Modify data type for metadata keys: Str -> Text
  thoth/storages/data/alembic/env.py
  thoth/storages/data/alembic/versions/8231fee9a210_modify_datatype_for_metadata.py
  thoth/storages/graph/models.py
Labels: approved, size/L

#1337 store database backup to ceph storage
  thoth/storages/__init__.py
  thoth/storages/ceph.py
  thoth/storages/graph_backup.py
  thoth/storages/result_base.py
Labels: approved, size/M

#1340 Gather document id from document_id field
  tests/data/schema/metadata_ok_1.json
  tests/data/schema/result_ok_analyzer_1.json
  tests/data/schema/result_ok_solver_1.json
  tests/test_result_base.py
  thoth/storages/exceptions.py
  thoth/storages/result_base.py
  thoth/storages/result_schema.py
Labels: approved, size/S

#1341 Fix Issue #1308 not iterable
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1346 Release of version 0.19.25
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1348 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M

#1350 Create index for get_depends_on query
  thoth/storages/data/alembic/versions/79e1d320db3d_create_index_for_get_depends_on_query.py
  thoth/storages/graph/models.py
Labels: approved, size/S
