Repository thoth-station/storages, pull requests merged in 2019-06, with the labels that each got.

#728 Provide OS version and name as a string
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#730 Check if the given package in the given version was solved by specific solver
  thoth/storages/graph/dgraph.py
Labels: approved, size/M

#731 Fix wrong variable reference
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#732 Automatic update of dependency boto3 from 1.9.159 to 1.9.161
  Pipfile.lock
Labels: bot

#733 Automatic update of dependency pytest from 4.5.0 to 4.6.2
  Pipfile.lock
Labels: bot

#734 Automatic update of dependency boto3 from 1.9.161 to 1.9.162
  Pipfile.lock
Labels: bot

#736 Release of version 0.14.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#737 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#738 Automatic update of dependency boto3 from 1.9.162 to 1.9.163
  Pipfile.lock
Labels: bot

#739 Automatic update of dependency boto3 from 1.9.163 to 1.9.164
  Pipfile.lock
Labels: bot

#740 Automatic update of dependency pydgraph from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: bot

#741 Automatic update of dependency boto3 from 1.9.164 to 1.9.165
  Pipfile.lock
Labels: bot

#742 Automatic update of dependency pytest from 4.6.2 to 4.6.3
  Pipfile.lock
Labels: bot

#743 Automatic update of dependency boto3 from 1.9.165 to 1.9.166
  Pipfile.lock
Labels: bot

#744 Automatic update of dependency boto3 from 1.9.166 to 1.9.167
  Pipfile.lock
Labels: bot

#745 Feature/improve pi
  docs/schema.dia
  docs/schema.png
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/L

#747 Automatic update of dependency boto3 from 1.9.167 to 1.9.168
  Pipfile.lock
Labels: bot

#748 New tests for inspection schema check before sync
  thoth/storages/inspection_schema.py
  thoth/storages/inspections.py
  thoth/storages/sync.py
Labels: approved, size/M

#749 Use index for int values of performance indicators
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/M

#750 Automatic update of dependency boto3 from 1.9.168 to 1.9.169
  Pipfile.lock
Labels: bot

#751 Automatic update of dependency boto3 from 1.9.169 to 1.9.170
  Pipfile.lock
Labels: bot

#752 Automatic update of dependency boto3 from 1.9.170 to 1.9.171
  Pipfile.lock
Labels: bot

#753 Automatic update of dependency boto3 from 1.9.171 to 1.9.172
  Pipfile.lock
Labels: bot

#754 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#755 Automatic update of dependency boto3 from 1.9.172 to 1.9.173
  Pipfile.lock
Labels: bot

#756 Automatic update of dependency pydgraph from 1.1.2 to 1.2.0
  Pipfile.lock
Labels: bot

#758 Automatic update of dependency boto3 from 1.9.173 to 1.9.174
  Pipfile.lock
Labels: bot

#759 Modified logic of the query
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#762 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#763 Release of version 0.14.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#760 Document local Dgraph instance setup
  README.rst
Labels: approved, size/S

#764 Automatic update of dependency boto3 from 1.9.174 to 1.9.175
  Pipfile.lock
Labels: bot

#767 Introduce pagination and solver_name filter
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#766 PackageAnalysisResultsStore is added
  thoth/storages/__init__.py
  thoth/storages/package_analyses.py
Labels: approved, do-not-merge/work-in-progress, size/M, size/S

#769 Release of version 0.14.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#770 Automatic update of dependency boto3 from 1.9.175 to 1.9.176
  Pipfile.lock
Labels: bot

#772 Automatic update of dependency boto3 from 1.9.176 to 1.9.178
  Pipfile.lock
Labels: bot

#773 Automatic update of dependency boto3 from 1.9.178 to 1.9.179
  Pipfile.lock
Labels: bot

#774 Automatic update of dependency boto3 from 1.9.179 to 1.9.180
  Pipfile.lock
Labels: bot

#775 Automatic update of dependency pytest from 4.6.3 to 5.0.0
  Pipfile.lock
Labels: bot
