Repository thoth-station/storages, pull requests merged in 2019-12, with the labels that each got.

#1353 Automatic update of dependency boto3 from 1.10.28 to 1.10.29
  Pipfile.lock
Labels: bot, size/M

#1354 Automatic update of dependency pyyaml from 5.1.2 to 5.2
  Pipfile.lock
Labels: bot, size/M

#1355 Automatic update of dependency boto3 from 1.10.29 to 1.10.30
  Pipfile.lock
Labels: bot, size/M

#1356 Correct staticmethod
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1357 Make some log info optional
  thoth/storages/data/alembic/env.py
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1358 Automatic update of dependency boto3 from 1.10.30 to 1.10.31
  Pipfile.lock
Labels: bot, size/S

#1359 Automatic update of dependency boto3 from 1.10.31 to 1.10.32
  Pipfile.lock
Labels: bot, size/S

#1360 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/XS

#1361 Automatic update of dependency boto3 from 1.10.32 to 1.10.33
  Pipfile.lock
Labels: bot, size/M

#1362 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/XS

#1363 Change Sphinx theme
  docs/source/conf.py
Labels: approved, size/XS

#1364 Provide OS release schema
  tests/data/schema/metadata_ok_1.json
  tests/data/schema/result_ok_analyzer_1.json
  tests/data/schema/result_ok_solver_1.json
  thoth/storages/result_schema.py
Labels: approved, size/M

#1349 Do not sync package errors if the given package is not provided
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1368 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#1369 Release of version 0.19.26
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1370 Automatic update of dependency boto3 from 1.10.33 to 1.10.34
  Pipfile.lock
Labels: bot, size/M

#1371 UBI:8 has optional variant_id
  thoth/storages/result_schema.py
Labels: approved, size/XS

#1373 Release of version 0.19.27
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#1366 Add aggregated_at column to CVE
  thoth/storages/data/alembic/versions/9b210f8d5c24_added_column_aggregated_at_to_cve.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, needs-schema-update, size/M

#1377 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#1378 Provide is_s2i flag for adviser runs
  thoth/storages/data/alembic/versions/fcac91b2a3f1_provide_is_s2i_flag_for_adviser_runs.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1375 Add deployment name to the result schema
  tests/data/schema/metadata_ok_1.json
  tests/data/schema/result_ok_analyzer_1.json
  tests/data/schema/result_ok_solver_1.json
  thoth/storages/result_schema.py
Labels: approved, size/S

#1376 Select distinct CVEs
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1379 Automatic update of dependency sqlalchemy-utils from 0.35.0 to 0.36.0
  Pipfile.lock
Labels: bot, size/S

#1381 Release of version 0.19.28
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1347 Adjust Python Package Metadata query
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1382 Automatic update of dependency boto3 from 1.10.34 to 1.10.35
  Pipfile.lock
Labels: bot, size/M

#1389 Fix Automatic Update Failure
  thoth/storages/graph/postgres.py
Labels: size/XS

#1388 Automatic update of dependency boto3 from 1.10.35 to 1.10.38
  Pipfile.lock
Labels: bot, size/M

#1390 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/XS

#1391 Automatic update of dependency boto3 from 1.10.38 to 1.10.39
  Pipfile.lock
Labels: bot, size/S

#1392 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/XS

#1393 Remove unused indexes in depends_on table
  thoth/storages/data/alembic/versions/3d0f03348c25_remove_unused_indexes_in_depends_on_.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1387 Introduce PyBench PI table and adjust sync logic for inspection
  thoth/storages/data/alembic/versions/f00fc22d1589_introduce_pi_pybench_for_python_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1394 Increase cache for caching solver errors
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1395 Automatic update of dependency sqlalchemy from 1.3.11 to 1.3.12
  Pipfile.lock
Labels: bot, size/M

#1397 Automatic update of dependency boto3 from 1.10.39 to 1.10.40
  Pipfile.lock
Labels: bot, size/S

#1396 Automatic update of dependency alembic from 1.3.1 to 1.3.2
  Pipfile.lock
Labels: bot, size/XS

#1400 Increment solver error cache
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1401 Release of version 0.19.29
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1402 Release of version 0.19.30
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1403 Automatic update of dependency boto3 from 1.10.40 to 1.10.41
  Pipfile.lock
Labels: bot, size/M

#1404 Automatic update of dependency boto3 from 1.10.41 to 1.10.42
  Pipfile.lock
Labels: bot, size/M

#1408 Automatic update of dependency boto3 from 1.10.42 to 1.10.43
  Pipfile.lock
Labels: bot, size/M

#1407 Do not dispose engine in destructor
  thoth/storages/graph/postgres.py
  thoth/storages/graph/sql_base.py
Labels: approved, size/XS

#1409 Do not show alembic info on configure_logger
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1410 Automatic update of dependency boto3 from 1.10.43 to 1.10.44
  Pipfile.lock
Labels: bot, size/M

#1411 Automatic update of dependency python-dateutil from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot, size/S

#1412 Automatic update of dependency sqlalchemy-utils from 0.36.0 to 0.36.1
  Pipfile.lock
Labels: bot, size/M

#1413 Automatic update of dependency boto3 from 1.10.44 to 1.10.45
  Pipfile.lock
Labels: bot, size/S

#1406 Implement rotation of backups
  README.rst
  thoth/storages/ceph.py
  thoth/storages/graph_backup.py
  thoth/storages/result_base.py
Labels: approved, size/L
