Repository thoth-station/storages, pull requests merged in 2019-10, with the labels that each got.

#1059 get_python_package_version_count() query
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1048 New query for number of versions per Python package name
  thoth/storages/graph/postgres.py
Labels: approved, size/M, size/XS

#1060 New python_package_versions_count functions
  thoth/storages/graph/postgres.py
Labels: approved, size/L, size/M

#1061 Created functions for get_python_packages cases
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1062 Generalized module variable for count
  thoth/storages/graph/postgres.py
Labels: approved, size/M, size/S

#1065 Automatic update of dependency boto3 from 1.9.239 to 1.9.240
  Pipfile.lock
Labels: bot

#1069 Minor fix to address typo
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1068 Implement a generic approach to sync any document
  thoth/storages/sync.py
Labels: approved, size/L

#1071 Remove obsolete exception
  thoth/storages/exceptions.py
Labels: approved, size/XS

#1070 Expose sync_documents outside of module
  thoth/storages/__init__.py
  thoth/storages/sync.py
Labels: approved, size/S

#1063 Sync duration
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1072 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#1073 Automatic update of dependency boto3 from 1.9.240 to 1.9.241
  Pipfile.lock
Labels: bot

#1075 Automatic update of dependency boto3 from 1.9.241 to 1.9.242
  Pipfile.lock
Labels: bot

#1067 Convert function according to new naming convention
  thoth/storages/graph/postgres.py
Labels: approved, size/L, size/M

#1066 Add examples to docstrings
  thoth/storages/graph/postgres.py
Labels: approved, size/M, size/XS

#1074 Add logic for syncing marker and extra
  thoth/storages/data/alembic/versions/f60593780969_add_markers_and_extra_needed_for_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M, size/S

#1076 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#1077 Automatic update of dependency boto3 from 1.9.242 to 1.9.243
  Pipfile.lock
Labels: bot

#1078 Automatic update of dependency sqlalchemy from 1.3.8 to 1.3.9
  Pipfile.lock
Labels: bot

#1079 Automatic update of dependency pytest-cov from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#1080 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#1064 Update functions for metrics according to naming convention
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1081 Fix performance indicator name
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1083 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#1085 Automatic update of dependency boto3 from 1.9.243 to 1.9.244
  Pipfile.lock
Labels: bot

#1086 Raise not found error if the given Python index is not found
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1087 State how to implement syncing logic for any workload job done in the cluster
  README.rst
Labels: approved, size/S

#1088 Remove old file for Dgraph related tests
  tests/graph/test_dgraph.py
Labels: approved, size/M

#1082 Changed schema and Added new Tables
  thoth/storages/data/alembic/versions/079e1d92f9d4_add_is_external_to_packageextractrun.py
  thoth/storages/data/alembic/versions/650a13fd0a08_robust_syncs.py
  thoth/storages/data/alembic/versions/9a8ce1e52efb_added_externalsoftwareenvironment_.py
  thoth/storages/exceptions.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L, size/XL

#1091 Add missing import
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1090 Remove unused import
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1092 Automatic update of dependency boto3 from 1.9.244 to 1.9.245
  Pipfile.lock
Labels: bot

#1095 Automatic update of dependency boto3 from 1.9.245 to 1.9.246
  Pipfile.lock
Labels: bot

#1096 Automatic update of dependency sqlalchemy from 1.3.9 to 1.3.10
  Pipfile.lock
Labels: bot

#1097 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#1084 Update solver functions
  thoth/storages/data/alembic/versions/331cbc965699_relax_constraints_for_.py
  thoth/storages/data/alembic/versions/a8a4748e85cb_hasartifact_linked_to_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/XL, size/XXL

#1099 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#1101 Consistenly sync index_url and package_version
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1103 Automatic update of dependency boto3 from 1.9.246 to 1.9.247
  Pipfile.lock
Labels: bot

#1104 Increase length file
  .coafile
Labels: approved, size/XS

#1107 Automatic update of dependency boto3 from 1.9.247 to 1.9.248
  Pipfile.lock
Labels: bot

#1108 Automatic update of dependency boto3 from 1.9.248 to 1.9.249
  Pipfile.lock
Labels: bot

#1111 Automatic update of dependency boto3 from 1.9.249 to 1.9.250
  Pipfile.lock
Labels: bot

#1113 Automatic update of dependency boto3 from 1.9.250 to 1.9.251
  Pipfile.lock
Labels: bot

#1116 Automatic update of dependency boto3 from 1.9.251 to 1.9.252
  Pipfile.lock
Labels: bot

#1110 New schema and sync in Solver for PythonPackageMetadata
  docs/syncs/thoth_sync_solver.graphml
  docs/syncs/thoth_sync_solver.jpg
  thoth/storages/data/alembic/versions/e05d6d95ea95_added_pythonpackagemetadata_table.py
  thoth/storages/exceptions.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1093 Created and Updated queries for analyzed packages
  docs/syncs/thoth_syncs_togheter.graphml
  docs/syncs/thoth_syncs_togheter.jpg
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L, size/XL, size/XXL

#1117 Fix error when case 3 is not declared yet
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1118 Fix query to retrieve number of unsolved packages
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1102 [WIP] Sync python interpreters
  thoth/storages/data/alembic/versions/74f68dabbb46_sync_python_interpreters.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/work-in-progress, size/M, work-in-progress

#1119 Fix signature of the private method - unsolved edge cases
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1120 Fix reference to variable in the query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1124 Fix multiple heads present
  thoth/storages/data/alembic/versions/e05d6d95ea95_added_pythonpackagemetadata_table.py
Labels: approved, size/XS

#1125 Allow nullable software environemnts in the schema
  thoth/storages/data/alembic/versions/54d50b0eeb33_allow_nullable_references_for_software_.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1128 Correct syncing issue
  docs/syncs/thoth_sync_package_extract.graphml
  docs/syncs/thoth_sync_package_extract.jpg
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/needs-rebase, size/L, size/S

#1130 Generic webhook updated to trigger the build from zuul
  .zuul.yaml
Labels: approved, do-not-merge/needs-rebase, size/XS

#1131 Automatic update of dependency boto3 from 1.9.252 to 1.9.253
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#1133 Automatic update of dependency psycopg2-binary from 2.8.3 to 2.8.4
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#1132 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#1135 Add missing columns to Python metadata
  thoth/storages/data/alembic/versions/295358ee27b1_add_description_content_type_column_to_.py
  thoth/storages/data/alembic/versions/d808ef831749_add_requires_python_column_to_python_.py
  thoth/storages/data/alembic/versions/ff18da87f7c1_add_project_url_column_to_python_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/needs-rebase, size/M

#1136 Add missing provides extra to Python metadata
  thoth/storages/data/alembic/versions/bcf07d69fc15_add_provides_extra_column_to_python_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/needs-rebase, size/M

#1137 Start using mypy for type checks
  Pipfile
  Pipfile.lock
  setup.py
  tests/base.py
  tests/graph/test_cache.py
  tests/test_analyses.py
  tests/test_buildlogs.py
  tests/test_ceph.py
  tests/test_result_base.py
  tests/test_result_schema.py
  tests/test_solvers.py
  tests/utils.py
Labels: approved, do-not-merge/needs-rebase, size/L

#1140 Automatic update of dependency boto3 from 1.9.253 to 1.10.0
  Pipfile.lock
Labels: bot

#1141 Drop cache support
  tests/graph/test_cache.py
  thoth/storages/__init__.py
  thoth/storages/cli.py
  thoth/storages/graph/__init__.py
  thoth/storages/graph/cache.py
  thoth/storages/graph/models_cache.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph_cache.py
Labels: approved, size/XXL

#1142 Introduce additional exception types for specific exceptions raised
  thoth/storages/exceptions.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph/sql_base.py
Labels: approved, do-not-merge/needs-rebase, size/M

#1143 Add support for extras in the Python package dependencies retrieval query
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/needs-rebase, size/M

#1144 Introduce query for checking marker evaluation results
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/needs-rebase, size/M

#1147 Handle issues in a better way
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1148 Automatic update of dependency boto3 from 1.10.0 to 1.10.1
  Pipfile.lock
Labels: bot

#1149 Automatic update of dependency methodtools from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#1152 Automatic update of dependency boto3 from 1.10.1 to 1.10.2
  Pipfile.lock
Labels: bot

#1154 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#1156 Release of version 0.19.11
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1159 Fix index url key in new solvers implementation
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1160 Fix version key dereference
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1145 Query environment markers stored in the database
  .coafile
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1161 Fix index url issue, now properly
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1162 consistency in using the variable force
  pyproject.toml
  thoth/storages/sync.py
Labels: approved, size/M

#1163 Fixing the func argument design
  thoth/storages/sync.py
Labels: approved, size/XS

#1164 Fixing the func argument names
  thoth/storages/sync.py
Labels: size/S

#1167 Release of version 0.19.12
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1169 Fix model assignment when syncing results of Python interpreters
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1170 Automatic update of dependency methodtools from 0.1.1 to 0.1.2
  Pipfile.lock
Labels: bot

#1171 podman compose in dev now
  Pipfile
  Pipfile.lock
  docker-compose.yaml
Labels: approved, size/S

#1173 Drop unique constraint in depends_on table
  thoth/storages/data/alembic/versions/a05ad6e1d0ca_drop_unique_constraint_in_depends_on_.py
  thoth/storages/graph/models.py
Labels: approved, size/S

#1139 Symbol-API
  thoth/storages/graph/postgres.py
Labels: size/M

#1177 Correct query to get metadata for Python Package
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1178 HasArtifact is linked with PythonPackageVersionEntity table
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1179 Revert "Symbol-API"
  thoth/storages/graph/postgres.py
Labels: size/M

#1180 Query to retrieve ML frameworks names
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1181 Automatic update of dependency boto3 from 1.10.2 to 1.10.3
  Pipfile.lock
Labels: bot

#1182 Automatic update of dependency boto3 from 1.10.3 to 1.10.4
  Pipfile.lock
Labels: bot

#1184 Issue warning on connection to the database if schema is not up2date
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1185 State maintainer and project url in setup.py
  setup.py
Labels: approved, size/XS

#1188 Query name convention
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1187 Release of version 0.19.13
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1189 Issue warning if the database schema is not initialized yet in connect
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1191 Keep Python package tuples positional arguments
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1192 Fix model for index url in the query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1193 Release of version 0.19.14
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1194 Automatic update of dependency boto3 from 1.10.4 to 1.10.5
  Pipfile.lock
Labels: bot

#1165 Sync container image size
  thoth/storages/data/alembic/versions/dd19dd789f6d_added_image_size_attribute_to_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M, size/XS

#1196 Fix retrieval of Python digests query
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1197 Start using mypy in strict mode
  Pipfile
  Pipfile.lock
  setup.py
  thoth/storages/graph/models_performance.py
Labels: approved, size/S

#1201 Automatic update of dependency boto3 from 1.10.5 to 1.10.6
  Pipfile.lock
Labels: bot

#1203 Automatic update of dependency alembic from 1.2.1 to 1.3.0
  Pipfile.lock
Labels: bot

#1204 Automatic update of dependency boto3 from 1.10.6 to 1.10.7
  Pipfile.lock
Labels: bot
