Repository thoth-station/storages, pull requests merged in 2019-03, with the labels that each got.

#550 Add missing ecosystem in query
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#552 Fix solver error handling
  thoth/storages/graph/janusgraph.py
Labels: size/S

#545 Automatic update of dependency boto3 from 1.9.98 to 1.9.101
  Pipfile.lock
Labels: bot

#554 Fix coala warnings
  thoth/storages/graph/janusgraph.py
Labels: size/S

#555 removed the trailing slash
  .zuul.yaml
Labels: approved, size/L, size/XS

#557 Use Sphinx to automatically generate docs
  .coafile
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: size/L

#558 Turn ram size into float to fix serialization/deserialization issues
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/S

#560 Add type to queries to hit index
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#561 Fix clash of runtime environment - model versus representing class
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/M

#562 Release of version 0.9.7
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#563 Remove duplicit method
  thoth/storages/graph/janusgraph.py
Labels: size/S

#564 Distinguish between runtime and buildtime environment
  thoth/storages/graph/janusgraph.py
Labels: size/M

#565 Make runtime and buildtime environment names shared
  thoth/storages/graph/janusgraph.py
  thoth/storages/graph/models.py
Labels: size/M

#567 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#568 Error in query get_analyzer_documents_count()
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#569 Update schema
  docs/schema.dia
  docs/schema.png
Labels: size/XS

#570 Adjust performance query to respect runtime environment
  thoth/storages/graph/janusgraph.py
Labels: size/M

#573 Be consistent with return type, return always nan
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#576 Adjust method signatures
  thoth/storages/graph/janusgraph.py
Labels: approved, size/M, size/XS
