Repository thoth-station/storages, pull requests merged in 2019-08, with the labels that each got.

#855 Corrected datatype-error for syncing
  thoth/storages/graph/performance.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/S

#857 Solved conflict pinning to older version
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#859 Release of version 0.18.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#860 Added missing inspection schema checks for voluptuous
  thoth/storages/inspection_schema.py
Labels: approved, size/XS

#862 Release of version 0.18.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#863 Release of version 0.18.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XL

#864 Automatic update of dependency boto3 from 1.9.199 to 1.9.200
  Pipfile.lock
Labels: bot

#865 Fix key error 'python'
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#866 Automatic update of dependency boto3 from 1.9.200 to 1.9.201
  Pipfile.lock
Labels: bot

#867 Automatic update of dependency boto3 from 1.9.201 to 1.9.202
  Pipfile.lock
Labels: bot

#869 Fixes Syncing of Package Extract results
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#870 Fix Package Analyzer results syncing
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#872 Automatic update of dependency boto3 from 1.9.202 to 1.9.203
  Pipfile.lock
Labels: bot

#873 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#875 Release of version 0.18.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#876 Automatic update of dependency boto3 from 1.9.203 to 1.9.204
  Pipfile.lock
Labels: bot

#877 Automatic update of dependency boto3 from 1.9.204 to 1.9.205
  Pipfile.lock
Labels: bot

#878 Use Python package name normalization from thoth-python module
  thoth/storages/graph/dgraph.py
Labels: size/XS

#879 Introduce a flag to retrieve only solved packages
  thoth/storages/graph/dgraph.py
Labels: approved, size/XS

#881 Release of version 0.18.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#882 Automatic update of dependency thoth-python from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot

#883 Automatic update of dependency boto3 from 1.9.205 to 1.9.206
  Pipfile.lock
Labels: bot

#884 Automatic update of dependency voluptuous from 0.11.5 to 0.11.7
  Pipfile.lock
Labels: bot

#885 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#886 WIP Retrieve packages that are not analyzed by Package-Analyzer
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#887 WIP Minor changes to the function which returns unanalyzed packages
  thoth/storages/graph/dgraph.py
Labels: approved, size/S

#889 Automatic update of dependency boto3 from 1.9.206 to 1.9.207
  Pipfile.lock
Labels: bot

#890 Fix query for retrieving unsolved Python packages
  thoth/storages/graph/dgraph.py
Labels: approved, size/M, size/S

#892 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#893 Release of version 0.18.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#894 Automatic update of dependency boto3 from 1.9.207 to 1.9.208
  Pipfile.lock
Labels: bot

#895 Automatic update of dependency boto3 from 1.9.208 to 1.9.209
  Pipfile.lock
Labels: bot

#896 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#897 Automatic update of dependency boto3 from 1.9.209 to 1.9.210
  Pipfile.lock
Labels: bot

#898 Automatic update of dependency boto3 from 1.9.210 to 1.9.211
  Pipfile.lock
Labels: bot

#899 Automatic update of dependency boto3 from 1.9.211 to 1.9.212
  Pipfile.lock
Labels: bot

#900 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#902 Automatic update of dependency boto3 from 1.9.212 to 1.9.213
  Pipfile.lock
Labels: bot

#904 Add is_provided flag
  thoth/storages/graph/dgraph.py
  thoth/storages/graph/models.py
  thoth/storages/graph/schema.rdf
Labels: approved, size/XS

#908 Automatic update of dependency boto3 from 1.9.213 to 1.9.214
  Pipfile.lock
Labels: bot

#910 Automatic update of dependency boto3 from 1.9.214 to 1.9.215
  Pipfile.lock
Labels: bot

#911 Automatic update of dependency boto3 from 1.9.215 to 1.9.216
  Pipfile.lock
Labels: bot

#912 Automatic update of dependency boto3 from 1.9.216 to 1.9.217
  Pipfile.lock
Labels: bot

#913 Automatic update of dependency boto3 from 1.9.217 to 1.9.218
  Pipfile.lock
Labels: bot

#914 Automatic update of dependency boto3 from 1.9.218 to 1.9.219
  Pipfile.lock
Labels: bot

#915 Automatic update of dependency boto3 from 1.9.219 to 1.9.220
  Pipfile.lock
Labels: bot

#916 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
