Repository thoth-station/storages, pull requests merged in 2019-01, with the labels that each got.

#442 Update README.rst
  README.rst
Labels: approved, size/XS

#439 Avoid goblin model details in output
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#438 Automatic update of dependency boto3 from 1.9.71 to 1.9.73
  Pipfile.lock
Labels: bot

#441 Disconnect in destructor
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#440 Minor fixes in method signatures
  thoth/storages/graph/janusgraph.py
Labels: approved, size/S

#443 Fix typo in retrieve_dependencies(...) query
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#444 Do not rely in Gremlin queries for order of received items
  thoth/storages/graph/janusgraph.py
Labels: size/XS

#446 Move OpenShift specific bits to OpenShift
  thoth/storages/graph/janusgraph.py
Labels: size/M

#454 Perform only graph or ceph sync if requested
  thoth/storages/sync.py
Labels: size/S

#450 Automatic update of dependency flexmock from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot

#449 Automatic update of dependency pytest-cov from 2.6.0 to 2.6.1
  Pipfile.lock
Labels: bot

#448 Automatic update of dependency pytest from 4.0.2 to 4.1.1
  Pipfile.lock
Labels: bot

#464 Automatic update of dependency boto3 from 1.9.83 to 1.9.84
  Pipfile.lock
Labels: bot

#468 Introduce flag exposing "existed" for Python package version
  thoth/storages/graph/janusgraph.py
Labels: size/S

#462 Provide method for solver name parsing
  thoth/storages/graph/janusgraph.py
Labels: size/S

#471 Introduce method for gathering packages known to thoth based on index
  thoth/storages/graph/janusgraph.py
Labels: size/S

#472 Introduce adapter for storing caching analysis ids based on image digest
  thoth/storages/__init__.py
  thoth/storages/analyses_by_digest.py
Labels: size/M

#458 Guard disconnect in destructor
  thoth/storages/graph/janusgraph.py
Labels: approved, size/XS

#475 Make graph optional parameter to reduce number of connections
  thoth/storages/sync.py
Labels: size/M
