Repository thoth-station/storages, pull requests merged in 2020-04, with the labels that each got.

#1697 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/S

#1698 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#1700 Automatic update of dependency boto3 from 1.12.33 to 1.12.34
  Pipfile.lock
Labels: bot, size/M

#1701 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#1702 Automatic update of dependency boto3 from 1.12.34 to 1.12.35
  Pipfile.lock
Labels: bot

#1703 Use RHEL 8
  .thoth.yaml
Labels: approved, size/XS

#1705 Automatic update of dependency boto3 from 1.12.35 to 1.12.36
  Pipfile.lock
Labels: bot, size/M

#1706 Automatic update of dependency pytest-mypy from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot, size/XS

#1707 Fix return value
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1708 Automatic update of dependency psycopg2-binary from 2.8.4 to 2.8.5
  Pipfile.lock
Labels: bot, size/M

#1709 Automatic update of dependency boto3 from 1.12.36 to 1.12.37
  Pipfile.lock
Labels: bot, size/S

#1710 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/S

#1711 Automatic update of dependency boto3 from 1.12.37 to 1.12.38
  Pipfile.lock
Labels: bot, size/S

#1712 Automatic update of dependency sqlalchemy from 1.3.15 to 1.3.16
  Pipfile.lock
Labels: bot, size/XS

#1713 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#1715 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#1714 Automatic update of dependency boto3 from 1.12.38 to 1.12.39
  Pipfile.lock
Labels: bot, size/S

#1726 Add logic for syncing reverse solver result
  thoth/storages/graph/postgres.py
  thoth/storages/revsolvers.py
  thoth/storages/sync.py
Labels: approved, size/L

#1727 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/L

#1730 Automatic update of dependency boto3 from 1.12.43 to 1.12.46
  Pipfile.lock
Labels: bot, size/M

#1731 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#1732 Automatic update of dependency pytest-mypy from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot, size/XS

#1725 Introduce get_dependents query
  thoth/storages/data/alembic/versions/a7442899ef28_add_indexes_needed_for_revsolver.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1736 Release of version 0.22.8
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#1738 Map ubi to rhel
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1743 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#1740 Automatic update of dependency boto3 from 1.12.46 to 1.12.47
  Pipfile.lock
Labels: bot, size/S

#1741 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/S

#1742 Release of version 0.22.9
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1746 Automatic update of dependency boto3 from 1.12.47 to 1.12.49
  Pipfile.lock
Labels: bot, size/M
