Repository thoth-station/storages, pull requests merged in 2020-06, with the labels that each got.

#1793 Automatic update of dependency boto3 from 1.13.19 to 1.13.20
  Pipfile.lock
Labels: bot, size/M

#1794 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#1795 Automatic update of dependency boto3 from 1.13.20 to 1.13.21
  Pipfile.lock
Labels: bot, size/S

#1796 Automatic update of dependency boto3 from 1.13.21 to 1.13.22
  Pipfile.lock
Labels: bot, size/M

#1798 Automatic update of dependency boto3 from 1.13.22 to 1.13.23
  Pipfile.lock
Labels: bot, size/M

#1799 Automatic update of dependency boto3 from 1.13.23 to 1.13.24
  Pipfile.lock
Labels: bot, size/M

#1797 Perform schema version check only if the database is available
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1800 Add platform to the schema
  thoth/storages/data/alembic/versions/9542eba46906_add_platform_for_dependencies.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1801 Add routines and index for platform manipulation
  thoth/storages/data/alembic/versions/7c261487d4d4_index_platform.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1803 create class for storing security indicators
  thoth/storages/__init__.py
  thoth/storages/si_bandit.py
  thoth/storages/si_cloc.py
Labels: approved, size/M

#1811 Automatic update of dependency boto3 from 1.13.24 to 1.14.1
  Pipfile.lock
Labels: bot, size/L

#1819 Update lock file to fix issues in CI
  Pipfile.lock
Labels: approved, size/L

#1818 Fix migration creating indexes
  thoth/storages/data/alembic/versions/9542eba46906_add_platform_for_dependencies.py
Labels: approved, size/XS

#1813 Release of version 0.23.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, bug

#1829 Add import or classes cannot be accessed
  thoth/storages/__init__.py
Labels: approved, size/XS

#1832 Remove duplicate imports
  thoth/storages/__init__.py
Labels: approved, size/XS

#1826 Implement adapters for inspections
  thoth/storages/inspections.py
Labels: approved, size/L

#1830 Release of version 0.23.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#1834 Add missing exports of inspection adapters
  thoth/storages/__init__.py
Labels: approved, size/XS

#1837 Move imports of amun to local scope
  thoth/storages/sync.py
Labels: approved, size/S

#1836 Introduce a method for checking if the given inspection exists
  thoth/storages/inspections.py
Labels: approved, size/XS

#1835 Fix computing batch size of inspection jobs
  thoth/storages/inspections.py
Labels: approved, size/XS

#1827 Remove parts moved to thoth-common
  thoth/storages/exceptions.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1838 No inspection result batch size
  thoth/storages/inspections.py
Labels: approved, size/S

#1842 Remove methods causing issues during initialization and creation of schema when database has different name than postgres
  thoth/storages/graph/postgres.py
  thoth/storages/graph/postgres_utils.py
Labels: approved

#1847 Automatic update of dependency thoth-common from 0.13.11 to 0.13.12
  Pipfile.lock
Labels: approved, bot

#1849 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: approved, bot

#1846 Automatic update of dependency boto3 from 1.14.4 to 1.14.9
  Pipfile.lock
Labels: approved, bot

#1850 Release of version 0.24.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#1857 Automatic update of dependency sqlalchemy from 1.3.17 to 1.3.18
  Pipfile.lock
Labels: approved, bot, size/L

#1862 New enum
  .gitignore
  thoth/storages/data/alembic/versions/d77154f3c15f_added_source_type_to_adviser_run_table.py
  thoth/storages/graph/enums.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1864 Automatic update of dependency boto3 from 1.14.9 to 1.14.13
  Pipfile.lock
Labels: approved, bot, size/M

#1865 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/S

#1866 Automatic update of dependency boto3 from 1.14.13 to 1.14.14
  Pipfile.lock
Labels: approved, bot, size/S

#1868 Fix missing normalize_os_version
  thoth/storages/graph/postgres.py
Labels: approved, size/M
