Repository thoth-station/storages, pull requests merged in 2020-11, with the labels that each got.

#2068 Automatic update of dependency boto3 from 1.16.8 to 1.16.9
  Pipfile.lock
Labels: approved, bot, size/S

#2070 Match location where provenance-checker documents are stored
  thoth/storages/provenance.py
Labels: approved, size/XS

#2077 Release of version 0.25.17
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#2076 Automatic update of dependency boto3 from 1.16.9 to 1.16.10
  Pipfile.lock
Labels: approved, bot, size/M

#2078 Provide a method for storing user requests
  thoth/storages/result_base.py
Labels: approved, kind/feature, size/S

#2081 Automatic update of dependency boto3 from 1.16.10 to 1.16.11
  Pipfile.lock
Labels: approved, bot, size/M

#2084 Release of version 0.26.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#2086 Adjust DM sync
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2087 Automatic update of dependency boto3 from 1.16.11 to 1.16.12
  Pipfile.lock
Labels: approved, bot, size/M

#2069 Raise an exception when the given record was not found
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2089 Automatic update of dependency boto3 from 1.16.12 to 1.16.15
  Pipfile.lock
Labels: approved, bot, size/M

#2090 Release of version 0.26.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#2046 Changes in schema for bug, internal trigger and data analysis
  Pipfile
  Pipfile.lock
  thoth/storages/data/alembic/versions/1a8150ac45e0_delete_to_refactor_schema_for_python_.py
  thoth/storages/data/alembic/versions/2d7ef94ff4dd_refactor_to_have_correct_schema_for_.py
  thoth/storages/data/alembic/versions/e7ebfc165a96_make_hash_columns_unique_and_add_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/XXL

#2092 check for cuda nvcc and found in file version
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2100 Release of version 0.27.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#2101 Install thoth-ssdeep requirement for thoth-storages
  requirements.txt
Labels: approved, size/XS

#2103 Release of version 0.27.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#2105 add function to run amcheck and check for db corruption
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2114 result must be cast to list
  thoth/storages/graph/postgres.py
Labels: approved, size/XS
