Repository thoth-station/storages, pull requests merged in 2020-07, with the labels that each got.

#1872 Automatic update of dependency thoth-common from 0.13.13 to 0.14.0
  Pipfile.lock
Labels: approved, bot, size/S

#1873 Sync si aggregated
  thoth/storages/__init__.py
  thoth/storages/data/alembic/versions/9aa4e29fa260_added_securityindicatoraggregatedrun_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/security_indicators.py
  thoth/storages/si_bandit.py
  thoth/storages/si_cloc.py
  thoth/storages/sync.py
Labels: approved, size/L

#1874 Automatic update of dependency boto3 from 1.14.14 to 1.14.17
  Pipfile.lock
Labels: approved, bot, size/M

#1875 Automatic update of dependency thoth-common from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/M

#1876 Automatic update of dependency sqlalchemy-utils from 0.36.6 to 0.36.7
  Pipfile.lock
Labels: approved, bot, size/M

#1880 Remove plural, only one build is done per inspection
  thoth/storages/inspections.py
Labels: approved, size/S

#1881 Adjust SI classes
  thoth/storages/__init__.py
  thoth/storages/security_indicators.py
  thoth/storages/sync.py
Labels: approved, size/L

#1882 Create queries for SI retrieval for certain package name, version , index
  thoth/storages/data/alembic/versions/10925df620b1_add_datetime_for_filtering_to_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1879 Introduce method for retrieving inspection ids and count
  thoth/storages/inspections.py
Labels: approved, size/M

#1878 Release of version 0.24.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#1886 Automatic update of dependency boto3 from 1.14.17 to 1.14.18
  Pipfile.lock
Labels: approved, bot, size/S

#1887 Automatic update of dependency sqlalchemy-utils from 0.36.7 to 0.36.8
  Pipfile.lock
Labels: approved, bot, size/S

#1891 Release of version 0.24.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1893 Do raise on counting, return zero instead
  thoth/storages/inspections.py
Labels: approved, size/XS

#1894 Automatic update of dependency boto3 from 1.14.18 to 1.14.19
  Pipfile.lock
Labels: approved, bot, size/S

#1892 Sync inspections results
  Pipfile
  Pipfile.lock
  thoth/storages/data/alembic/versions/d6d0b20ec650_add_result_number_to_inspectionrun.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
  thoth/storages/sync.py
Labels: approved, size/L

#1896 Release of version 0.24.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1897 Map old domain to new
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1898 Automatic update of dependency boto3 from 1.14.19 to 1.14.21
  Pipfile.lock
Labels: approved, bot, size/L

#1899 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#1900 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1901 Default platform if not available in the solver document
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1903 Automatic update of dependency boto3 from 1.14.21 to 1.14.22
  Pipfile.lock
Labels: approved, bot, size/S

#1904 Release of version 0.24.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1908 Automatic update of dependency boto3 from 1.14.22 to 1.14.26
  Pipfile.lock
Labels: approved, bot, size/L

#1907 Use method from thoth-common
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1910 Release of version 0.24.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1911 Use postgres:10.12 in podman-compose as in the cluster
  docker-compose.yaml
Labels: approved, size/XS

#1912 Automatic update of dependency boto3 from 1.14.26 to 1.14.28
  Pipfile.lock
Labels: approved, bot, size/L

#1914 Automatic update of dependency boto3 from 1.14.28 to 1.14.30
  Pipfile.lock
Labels: approved, bot, size/M

#1915 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/S

#1919 adding aggregated points to wrong location
  thoth/storages/sync.py
Labels: approved, size/XS

#1920 Automatic update of dependency boto3 from 1.14.30 to 1.14.31
  Pipfile.lock
Labels: approved, bot, size/M

#1921 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1923 Release of version 0.25.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#1924 Automatic update of dependency thoth-common from 0.15.0 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/S
