Repository thoth-station/storages, pull requests merged in 2020-03, with the labels that each got.

#1637 Remove typeshed dev dependency
  Pipfile
  Pipfile.lock
Labels: approved

#1638 Automatic update of dependency boto3 from 1.12.16 to 1.12.18
  Pipfile.lock
Labels: bot, size/S

#1640 Automatic update of dependency click from 7.0 to 7.1.1
  Pipfile.lock
Labels: bot, size/S

#1639 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/XS

#1641 Automatic update of dependency sqlalchemy from 1.3.13 to 1.3.14
  Pipfile.lock
Labels: bot, size/XS

#1642 Automatic update of dependency sqlalchemy from 1.3.14 to 1.3.15
  Pipfile.lock
Labels: bot, size/M

#1643 Automatic update of dependency boto3 from 1.12.18 to 1.12.19
  Pipfile.lock
Labels: bot, size/M

#1644 Automatic update of dependency boto3 from 1.12.19 to 1.12.20
  Pipfile.lock
Labels: bot, size/S

#1647 Automatic update of dependency pyyaml from 5.3 to 3.13
  Pipfile.lock
Labels: bot, size/M

#1648 Automatic update of dependency boto3 from 1.12.20 to 1.12.21
  Pipfile.lock
Labels: bot, size/S

#1649 Automatic update of dependency pytest-mypy from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot, size/S

#1650 Automatic update of dependency sqlalchemy-utils from 0.36.1 to 0.36.2
  Pipfile.lock
Labels: bot, size/XS

#1646 Automatic update of dependency pytest from 5.3.5 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#1651 Automatic update of dependency boto3 from 1.12.21 to 1.12.22
  Pipfile.lock
Labels: bot, size/M

#1652 Add empty env template
  .env.template
Labels: approved, size/M

#1653 Automatic update of dependency boto3 from 1.12.22 to 1.12.23
  Pipfile.lock
Labels: bot, size/L

#1654 Automatic update of dependency sqlalchemy-utils from 0.36.2 to 0.36.3
  Pipfile.lock
Labels: bot, size/XS

#1656 Automatic update of dependency boto3 from 1.12.23 to 1.12.24
  Pipfile.lock
Labels: bot, size/S

#1658 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/S

#1660 Automatic update of dependency boto3 from 1.12.24 to 1.12.25
  Pipfile.lock
Labels: bot, size/M

#1659 Reduce number of queries for environment markers by caching results
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1662 Automatic update of dependency alembic from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: bot, size/XS

#1663 Release of version 0.22.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#1664 Release of version 0.22.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1665 Link Adviser Run with Python Package Versio Entity
  thoth/storages/data/alembic/versions/74254b596f00_added_new_table_to_link_adviser_run_and_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1666 Automatic update of dependency boto3 from 1.12.25 to 1.12.26
  Pipfile.lock
Labels: bot

#1618 API calls for package-update-consumer
  thoth/storages/graph/postgres.py
Labels: size/M

#1670 Automatic update of dependency boto3 from 1.12.26 to 1.12.27
  Pipfile.lock
Labels: bot, size/M

#1672 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot

#1673 Automatic update of dependency boto3 from 1.12.27 to 1.12.28
  Pipfile.lock
Labels: bot

#1676 Automatic update of dependency thoth-common from 0.10.12 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#1677 Automatic update of dependency boto3 from 1.12.28 to 1.12.29
  Pipfile.lock
Labels: bot, size/M

#1678 Automatic update of dependency thoth-common from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/XS

#1679 Automatic update of dependency pyyaml from 5.3.1 to 3.13
  Pipfile.lock
Labels: bot, size/M

#1680 Automatic update of dependency thoth-common from 0.12.2 to 0.12.3
  Pipfile.lock
Labels: bot, size/S

#1668 Modify schema and logic to sync adviser run
  thoth/storages/data/alembic/versions/0ea53ec16d6b_use_text_instead_of_strings_all_over_.py
  thoth/storages/data/alembic/versions/125a71b49a50_add_parameters_to_deal_with_unsolved_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/XXL

#1681 Automatic update of dependency boto3 from 1.12.29 to 1.12.30
  Pipfile.lock
Labels: bot, size/M

#1682 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/XS

#1671 Package update api
  thoth/storages/data/alembic/versions/ecb0ca258835_flag_for_if_specific_hash_has_gone_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: size/L

#1684 Correct README for graph-backup-job
  README.rst
Labels: approved

#1683 Minor correction for package-update-api
  thoth/storages/data/alembic/versions/ecb0ca258835_flag_for_if_specific_hash_has_gone_.py
  thoth/storages/graph/models.py
Labels: approved, size/S

#1686 Fix obtaining model attributes in model.to_dict()
  thoth/storages/graph/models_base.py
Labels: approved, size/S

#1689 Release of version 0.22.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#1690 Automatic update of dependency boto3 from 1.12.30 to 1.12.31
  Pipfile.lock
Labels: bot, size/M

#1691 Drop methods tools to gain performance
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/storages/graph/postgres.py
Labels: approved

#1693 Release of version 0.22.7
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1695 Automatic update of dependency boto3 from 1.12.31 to 1.12.32
  Pipfile.lock
Labels: bot, size/L

#1694 add assignments to query
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1696 Automatic update of dependency boto3 from 1.12.32 to 1.12.33
  Pipfile.lock
Labels: bot, size/M
