Repository thoth-station/storages, pull requests merged in 2020-08, with the labels that each got.

#1927 Add long_description_content_type
  setup.py
Labels: approved, size/XS

#1929 add cache and return None if empty
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1931 Automatic update of dependency boto3 from 1.14.31 to 1.14.43
  Pipfile.lock
Labels: approved, bot, size/L

#1932 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/L

#1933 Automatic update of dependency pytest from 6.0.0 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/L

#1935 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/L

#1938 Release of version 0.25.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#1944 Fix revsolver syncing logic
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1940 Add security and performance database enums
  thoth/storages/data/alembic/versions/83e2900c3721_add_performance_and_security_enums_for_.py
  thoth/storages/graph/enums.py
Labels: approved, size/M

#1917 Add information about heads on schema up2date check
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1941 Automatic update of dependency boto3 from 1.14.43 to 1.14.45
  Pipfile.lock
Labels: approved, bot, size/M

#1942 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/S

#1946 Release of version 0.25.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1943 Automatic update of dependency sqlalchemy from 1.3.18 to 1.3.19
  Pipfile.lock
Labels: approved, bot, size/L

#1949 Fix logging error when database schema is not up2date
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1950 Automatic update of dependency boto3 from 1.14.45 to 1.14.46
  Pipfile.lock
Labels: approved, bot, size/S

#1953 Release of version 0.25.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1956 Automatic update of dependency boto3 from 1.14.46 to 1.14.47
  Pipfile.lock
Labels: approved, bot, size/M

#1955 Propagate platform when syncing revsolver results
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1954 Propagate platform information in dependents query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1958 Release of version 0.25.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1964 query.all returns type List[result] not List[str]
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1968 Release of version 0.25.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1969 Automatic update of dependency boto3 from 1.14.47 to 1.14.49
  Pipfile.lock
Labels: approved, bot, size/L

#1970 Automatic update of dependency pytest-mypy from 0.6.2 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/S
