Repository thoth-station/storages, pull requests merged in 2020-01, with the labels that each got.

#1416 Sync package version requested rather than package version reported
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1414 Optimize marker evaluation result query for adviser
  thoth/storages/data/alembic/versions/fd7771734460_optimize_marker_evaluation_result_query_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1418 Release of version 0.20.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1419 Automatic update of dependency boto3 from 1.10.45 to 1.10.46
  Pipfile.lock
Labels: bot, size/L

#1421 Fix keyword argument passing
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1423 Release of version 0.20.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1424 Remove string size limitations from depends_on table
  thoth/storages/data/alembic/versions/9fea7ca59f56_remove_string_size_limitation_from_.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1426 Happy new year!
  docs/source/conf.py
  tests/__init__.py
  tests/base.py
  tests/graph/__init__.py
  tests/test_analyses.py
  tests/test_buildlogs.py
  tests/test_ceph.py
  tests/test_result_base.py
  tests/test_result_schema.py
  tests/test_solvers.py
  tests/utils.py
  thoth/storages/__init__.py
  thoth/storages/advisers.py
  thoth/storages/advisers_cache.py
  thoth/storages/analyses.py
  thoth/storages/analyses_by_digest.py
  thoth/storages/analyses_cache.py
  thoth/storages/base.py
  thoth/storages/buildlogs.py
  thoth/storages/buildlogs_analyses.py
  thoth/storages/buildlogs_analyses_cache.py
  thoth/storages/ceph.py
  thoth/storages/ceph_cache.py
  thoth/storages/cli.py
  thoth/storages/dependency_monkey_reports.py
  thoth/storages/exceptions.py
  thoth/storages/graph/__init__.py
  thoth/storages/graph/enums.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_base.py
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
  thoth/storages/graph/query_result_base.py
  thoth/storages/graph/sql_base.py
  thoth/storages/graph_backup.py
  thoth/storages/inspection_schema.py
  thoth/storages/inspections.py
  thoth/storages/observations.py
  thoth/storages/package_analyses.py
  thoth/storages/provenance.py
  thoth/storages/provenance_cache.py
  thoth/storages/result_base.py
  thoth/storages/result_schema.py
  thoth/storages/solvers.py
  thoth/storages/sync.py
Labels: approved, size/M

#1427 Release of version 0.20.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1429 Fix syncs in versions
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1431 Release of version 0.20.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1432 Fix wrong argument name propagated
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1434 Release of version 0.20.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1440 Automatic update of dependency boto3 from 1.10.46 to 1.10.47
  Pipfile.lock
Labels: bot, size/L

#1441 Automatic update of dependency pyyaml from 5.2 to 5.3
  Pipfile.lock
Labels: bot, size/M

#1442 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/XS

#1443 Introduce software environment specific queries
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1444 Missing randomize
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1445 correct typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS

#1446 Correct key from inspection output
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1448 Automatic update of dependency thoth-python from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/XS

#1449 Release of version 0.20.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1451 Fix syncing external software environments coming from adviser
  thoth/storages/graph/postgres.py
Labels: size/M

#1453 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#1454 Release of version 0.20.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1455 Automatic update of dependency boto3 from 1.10.47 to 1.10.48
  Pipfile.lock
Labels: bot, size/S

#1458 Automatic update of dependency thoth-python from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot, size/S

#1456 Create index for CVE step to omit sequence scan
  thoth/storages/data/alembic/versions/af2b9e09e53e_create_index_for_cve_step.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1460 Fix advised software stack sync
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1457 Drop id columns on relation tables
  thoth/storages/data/alembic/versions/d0ebc816243c_drop_id_on_relation_tables.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1462 Automatic update of dependency boto3 from 1.10.48 to 1.10.49
  Pipfile.lock
Labels: bot, size/S

#1463 Automatic update of dependency thoth-python from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot, size/XS

#1465 Automatic update of dependency boto3 from 1.10.49 to 1.10.50
  Pipfile.lock
Labels: bot, size/M

#1466 Release of version 0.21.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1467 Automatic update of dependency amun from 0.2.7 to 0.3.0
  Pipfile.lock
Labels: bot, size/XS

#1471 Correct inspection sync key
  thoth/storages/graph/models_performance.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1473 Adjust syncing logic of Dependency Monkey documents based on the curr…
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1475 Fix parameter name for syncing provenance-checker documents
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1474 Provide environment variable marker flag when retrieving transitive deps
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1478 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#1479 Release of version 0.21.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1480 Release of version 0.21.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1481 Adjust datatype for conv PI to sync inspection results
  thoth/storages/data/alembic/versions/1fbd52a03c73_adjust_types_for_conv_pi.py
  thoth/storages/graph/models_performance.py
Labels: approved, size/M

#1483 Release of version 0.21.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#1484 Automatic update of dependency boto3 from 1.10.50 to 1.11.0
  Pipfile.lock
Labels: bot, size/M

#1485 Introduce a query for retrieving Python package entity names
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1487 Query for index_url before creating index
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1489 Release of version 0.21.4
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1488 Consider only enabled indexes in unsolved queries
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1490 Alembic didn't create correct change in schema
  thoth/storages/data/alembic/versions/1fbd52a03c73_adjust_types_for_conv_pi.py
Labels: approved, size/XS

#1492 Automatic update of dependency amun from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot, size/L

#1493 Release of version 0.21.5
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1494 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/S

#1495 Fix query for enabled index
  thoth/storages/graph/postgres.py
Labels: size/XS

#1498 Release of version 0.21.6
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1499 Adjust index for PPV combinations
  thoth/storages/data/alembic/versions/b91c11e75551_recreate_indexes_for_python_package_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/models_base.py
Labels: approved, size/M

#1500 Add index for solved table - it optimizes the has_solver_error query in adviser
  thoth/storages/data/alembic/versions/7d970baad7f2_create_index_for_solved_on_version_id.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1501 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#1502 Automatic update of dependency boto3 from 1.11.1 to 1.11.2
  Pipfile.lock
Labels: bot, size/M

#1503 Create index for has_artifact table
  thoth/storages/data/alembic/versions/bb26306538f0_create_indexes_for_has_artifact_table.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1504 Introduce a way to parametrize memory cache size
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1506 Release of version 0.21.7
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1507 Automatic update of dependency boto3 from 1.11.2 to 1.11.3
  Pipfile.lock
Labels: bot, size/M

#1508 Automatic update of dependency amun from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: bot, bug, size/XS

#1512 Automatic update of dependency thoth-common from 0.9.26 to 0.9.28
  Pipfile.lock
Labels: bot, size/S

#1510 Auto pip and black formatting
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/sync.py
Labels: approved, size/XXL

#1515 Normalize OS version by discarding any minor release in RHEL release string
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1516 Automatic update of dependency amun from 0.3.2 to 0.3.3
  Pipfile.lock
Labels: bot, size/XS

#1518 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#1520 Automatic update of dependency boto3 from 1.11.4 to 1.11.5
  Pipfile.lock
Labels: bot, size/S

#1523 Set Packages Extract flag is_external to True always
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1522 Missing change in query name to follow query name convention
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1524 Add missing key to sync inspections
  thoth/storages/inspection_schema.py
Labels: approved, size/XS

#1525 Adjust parameter in query for PI
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1526 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#1527 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#1528 Automatic update of dependency boto3 from 1.11.5 to 1.11.6
  Pipfile.lock
Labels: bot, size/M

#1530 Release of version 0.21.8
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1531 Release of version 0.21.9
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1532 Automatic update of dependency amun from 0.3.3 to 0.3.4
  Pipfile.lock
Labels: bot, size/XS

#1534 Make keys Optional
  thoth/storages/inspection_schema.py
Labels: approved, size/S

#1537 Release of version 0.21.10
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1509 Added build log analysis result observations to graph database
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/sync.py
Labels: approved, size/L

#1536 Automatic update of dependency amun from 0.3.4 to 0.3.5
  Pipfile.lock
Labels: bot, size/S

#1538 Automatic update of dependency boto3 from 1.11.6 to 1.11.7
  Pipfile.lock
Labels: bot, size/M

#1539 added some files to gitignore
  .gitignore
Labels: approved, size/XS

#1542 Automatic update of dependency alembic from 1.3.2 to 1.3.3
  Pipfile.lock
Labels: bot, size/S

#1541 Automatic update of dependency sqlalchemy from 1.3.12 to 1.3.13
  Pipfile.lock
Labels: bot, size/XS

#1543 Automatic update of dependency boto3 from 1.11.7 to 1.11.8
  Pipfile.lock
Labels: bot, size/M

#1544 Automatic update of dependency boto3 from 1.11.8 to 1.11.9
  Pipfile.lock
Labels: bot, size/M

#1545 Add missing keys to inspection schema validation
  thoth/storages/inspection_schema.py
Labels: approved, size/XS

#1547 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#1549 Release of version 0.21.11
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#1548 Automatic update of dependency amun from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot, size/XS

#1550 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#1552 Automatic update of dependency amun from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot, size/S

#1553 Automatic update of dependency amun from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot, size/XS

#1556 Fixed missing index issue
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1557 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#1558 Fix method call to serialize models
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1559 Fix reference to variable
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1560 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M

#1561 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
