Repository thoth-station/storages, pull requests merged in 2020-10, with the labels that each got.

#2037 Adjust docstring revision
  thoth/storages/data/alembic/versions/4461784e248a_added_kebechet_manager_and_last_run_.py
Labels: approved, size/XS

#2043 Automatic update of dependency boto3 from 1.15.9 to 1.15.11
  Pipfile.lock
Labels: approved, bot, size/M

#2044 Release of version 0.25.15
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#2050 Fix cache handling and add ability to drop the cache
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2049 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/L

#2048 Automatic update of dependency boto3 from 1.15.11 to 1.15.16
  Pipfile.lock
Labels: approved, bot, size/L

#2051 Automatic update of dependency sqlalchemy from 1.3.19 to 1.3.20
  Pipfile.lock
Labels: approved, bot, size/L

#2052 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/M

#2055 Automatic update of dependency boto3 from 1.15.16 to 1.16.0
  Pipfile.lock
Labels: approved, bot, size/L

#2056 Automatic update of dependency thoth-common from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/XS

#2057 Automatic update of dependency boto3 from 1.16.0 to 1.16.6
  Pipfile.lock
Labels: approved, bot, size/L

#2054 add error flag to si-sync
  thoth/storages/data/alembic/versions/342d45db2dc2_add_flag_to_indicate_failed_si.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, hacktoberfest-accepted, priority/critical-urgent, size/M

#2060 Automatic update of dependency boto3 from 1.16.6 to 1.16.8
  Pipfile.lock
Labels: approved, bot, size/L

#2061 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#2062 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#2064 Adjust alembic migration
  thoth/storages/data/alembic/versions/342d45db2dc2_add_flag_to_indicate_failed_si.py
Labels: approved, size/XS

#2065 Adjust query filters
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2067 Release of version 0.25.16
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S
