Repository thoth-station/storages, pull requests merged in 2020-09, with the labels that each got.

#1971 State how to install podman and podman-compose
  README.rst
Labels: approved, size/XS

#1972 Automatic update of dependency boto3 from 1.14.49 to 1.14.53
  Pipfile.lock
Labels: approved, bot, size/M

#1973 Automatic update of dependency thoth-common from 0.16.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/M

#1977 Relock the pipfile.lock
  Pipfile.lock
Labels: approved, size/L

#1976 Introduce query for document ids with solver error
  thoth/storages/graph/postgres.py
Labels: approved, size/XL

#1981 Automatic update of dependency boto3 from 1.14.57 to 1.14.58
  Pipfile.lock
Labels: approved, bot, size/L

#1982 Automatic update of dependency thoth-common from 0.17.3 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1975 Make package version and package index optional in get_depends_on
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1983 Automatic update of dependency thoth-common from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/XS

#1963 Get si unsolved
  thoth/storages/data/alembic/versions/84588707e6ba_added_a_relation_between_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1986 Release of version 0.25.7
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#1987 Add queries for SI metrics
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1988 Automatic update of dependency boto3 from 1.14.58 to 1.14.60
  Pipfile.lock
Labels: approved, bot, size/M

#1989 Automatic update of dependency thoth-common from 0.18.1 to 0.18.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1990 Automatic update of dependency alembic from 1.4.2 to 1.4.3
  Pipfile.lock
Labels: approved, bot, size/XS

#1993 Release of version 0.25.8
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#1994 Remove package-analyzer related bits
  thoth/storages/__init__.py
  thoth/storages/data/alembic/versions/6389973bd8b6_remove_package_analyzer.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/package_analyses.py
  thoth/storages/sync.py
Labels: approved, size/XL

#1997 Add query for adviser run per source type
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1998 Automatic update of dependency boto3 from 1.14.60 to 1.14.61
  Pipfile.lock
Labels: approved, bot, size/L

#1999 Automatic update of dependency thoth-common from 0.18.2 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/L

#1996 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/M

#2001 Release of version 0.25.9
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot

#2002 Fix sync for security
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2004 Automatic update of dependency boto3 from 1.14.61 to 1.14.62
  Pipfile.lock
Labels: approved, bot, size/M

#2005 Release of version 0.25.10
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#2009 Automatic update of dependency boto3 from 1.14.62 to 1.14.63
  Pipfile.lock
Labels: approved, bot, size/M

#2010 Invert order to allow sync
  thoth/storages/data/alembic/versions/6389973bd8b6_remove_package_analyzer.py
Labels: approved, size/XS

#2012 Automatic update of dependency boto3 from 1.14.63 to 1.15.1
  Pipfile.lock
Labels: approved, bot, size/M

#2011 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#2013 Adjust SI queries
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2015 Release of version 0.25.11
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#2021 add flag for missing src distro
  thoth/storages/data/alembic/versions/c8017a5b43f1_add_flag_to_indicate_missing_source_code.py
  thoth/storages/graph/models.py
Labels: approved, size/S

#2017 Automatic update of dependency boto3 from 1.15.1 to 1.15.6
  Pipfile.lock
Labels: approved, bot, size/L

#2018 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#2019 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/S

#2020 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/S

#2022 add func for updating downloadable function
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2025 Correct docstring
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2026 Automatic update of dependency boto3 from 1.15.6 to 1.15.7
  Pipfile.lock
Labels: approved, bot, size/M

#2027 Adjust query for new flag is_downloadable
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2029 Release of version 0.25.12
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/S

#2030 Rename flag to be generalized
  thoth/storages/data/alembic/versions/cd34fd8a5a90_rename_si_downloadable_flag_to_is_si_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2032 Release of version 0.25.13
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: approved, bot, size/XS

#2024 Added changes to kebechet model
  thoth/storages/data/alembic/versions/4461784e248a_added_kebechet_manager_and_last_run_.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#2033 change flag name and alembic commands
  thoth/storages/data/alembic/versions/b9f960cdd223_change_flag_to_provides_source_distro.py
  thoth/storages/data/alembic/versions/cd34fd8a5a90_rename_si_downloadable_flag_to_is_si_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2034 Automatic update of dependency boto3 from 1.15.7 to 1.15.8
  Pipfile.lock
Labels: approved, bot, size/M

#2035 Alembic timeline fix
  thoth/storages/data/alembic/versions/4461784e248a_added_kebechet_manager_and_last_run_.py
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2036 Correct queries after changes in schema
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2041 Automatic update of dependency boto3 from 1.15.8 to 1.15.9
  Pipfile.lock
Labels: approved, bot, size/S

#2040 Release of version 0.25.14
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S
