Repository thoth-station/storages, pull requests merged in 2020-02, with the labels that each got.

#1562 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#1563 Created query to monitor bloat data
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1564 Automatic update of dependency boto3 from 1.11.9 to 1.11.10
  Pipfile.lock
Labels: bot, size/M

#1565 Automatic update of dependency alembic from 1.3.3 to 1.4.0
  Pipfile.lock
Labels: bot, size/XS

#1311 Simplified API functions
  thoth/storages/data/alembic/versions/6ce8fb9b3329_add_indexes_for_abi_compatability_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1572 Fix OS name synced in container image analysis
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1569 No need to query for package extract run - software environment can be directly used
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1566 Fix index creation for symbols queries
  thoth/storages/data/alembic/versions/0c8eab5d4197_add_indexes_for_abi_compatability_.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1575 Fix inspection syncing for RHEL
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1576 Set default to False to reduce logging
  thoth/storages/data/alembic/env.py
Labels: approved, size/XS

#1554 Sync missing packages if adviser failed due to unknown dependencies
  thoth/storages/graph/postgres.py
Labels: size/M

#1568 Fix package symbols query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1578 Automatic update of dependency boto3 from 1.11.10 to 1.11.11
  Pipfile.lock
Labels: bot, size/M

#1579 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#1580 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#1581 Automatic update of dependency boto3 from 1.11.11 to 1.11.12
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/M

#1582 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#1583 Automatic update of dependency boto3 from 1.11.12 to 1.11.13
  Pipfile.lock
Labels: bot, size/S

#1585 Release of version 0.22.0
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/M

#1588 Automatic update of dependency boto3 from 1.11.13 to 1.11.14
  Pipfile.lock
Labels: bot, size/M

#1587 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#1590 Added option to exclude models from the generated schema
  thoth/storages/cli.py
Labels: approved, size/M

#1591 Automatic update of dependency boto3 from 1.11.14 to 1.11.15
  Pipfile.lock
Labels: bot, size/M

#1592 Add check in sync when report is not provided by Adviser
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1595 Release of version 0.22.1
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1593 All counts optional
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1596 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#1597 Automatic update of dependency boto3 from 1.11.15 to 1.11.16
  Pipfile.lock
Labels: bot, size/S

#1599 Release of version 0.22.2
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/XS

#1600 Automatic update of dependency boto3 from 1.11.16 to 1.11.17
  Pipfile.lock
Labels: bot, size/S

#1601 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#1603 Automatic update of dependency boto3 from 1.11.17 to 1.12.0
  Pipfile.lock
Labels: bot

#1577 Address issue #1573
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1605 Automatic update of dependency boto3 from 1.12.0 to 1.12.1
  Pipfile.lock
Labels: bot, size/M

#1604 Parse py version
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1606 Automatic update of dependency boto3 from 1.12.1 to 1.12.2
  Pipfile.lock
Labels: bot, size/M

#1610 Automatic update of dependency amun from 0.3.8 to 0.4.0
  Pipfile.lock
Labels: bot, size/S

#1612 Automatic update of dependency boto3 from 1.12.2 to 1.12.3
  Pipfile.lock
Labels: bot, size/M

#1611 flag for missing package version
  thoth/storages/data/alembic/versions/ed56455efd82_add_flag_for_missing_package_version.py
  thoth/storages/graph/models.py
Labels: approved, size/S

#1613 Automatic update of dependency boto3 from 1.12.3 to 1.12.4
  Pipfile.lock
Labels: bot, size/S

#1614 Automatic update of dependency boto3 from 1.12.4 to 1.12.5
  Pipfile.lock
Labels: bot, size/M

#1615 Automatic update of dependency pytest-mypy from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot, size/M

#1616 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/S

#1619 Automatic update of dependency boto3 from 1.12.5 to 1.12.6
  Pipfile.lock
Labels: bot, size/M

#1617 Move import to local use
  thoth/storages/sync.py
Labels: size/XS

#1622 Automatic update of dependency amun from 0.4.0 to 0.4.3
  Pipfile.lock
Labels: bot, size/S

#1624 Automatic update of dependency boto3 from 1.12.6 to 1.12.7
  Pipfile.lock
Labels: bot, size/S

#1623 Release of version 0.22.3
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1626 Fix database migration for python_package_version.is_missing
  thoth/storages/data/alembic/versions/ed56455efd82_add_flag_for_missing_package_version.py
Labels: approved, size/XS

#1627 Automatic update of dependency boto3 from 1.12.7 to 1.12.8
  Pipfile.lock
Labels: bot, size/M

#1630 Automatic update of dependency boto3 from 1.12.8 to 1.12.9
  Pipfile.lock
Labels: bot, size/M

#1629 Naming convention for query in Thoth Knowledge Graph
  README.rst
  docs/conventions/README.md
Labels: approved, size/M

#1631 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/XS

#1632 Automatic update of dependency boto3 from 1.12.9 to 1.12.10
  Pipfile.lock
Labels: bot, size/S

#1633 Automatic update of dependency boto3 from 1.12.10 to 1.12.11
  Pipfile.lock
Labels: bot
