Repository thoth-station/storages, pull requests merged in 2020-12, with the labels that each got.

#2121 bump python version
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#2129 Adjust constraint on py38
  Pipfile.lock
Labels: approved, size/L

#2125 Make parameter public
  README.rst
  thoth/storages/__init__.py
  thoth/storages/sync.py
Labels: approved, size/S

#2137 Correct error in sorting, use sort()
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2141 Use proper naming convention of type 6
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2144 Use sort() correctly
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2134 Add get active installations method
  thoth/storages/graph/postgres.py
Labels: approved, do-not-merge/hold, kind/feature, sig/knowledge-graph, size/S

#2148 Add get_origin_count_per_source_type method
  thoth/storages/graph/postgres.py
Labels: approved, size/M
