Repository thoth-station/storages, pull requests merged in 2020-05, with the labels that each got.

#1750 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#1752 Automatic update of dependency boto3 from 1.13.2 to 1.13.3
  Pipfile.lock
Labels: bot, size/S

#1753 Automatic update of dependency boto3 from 1.13.3 to 1.13.4
  Pipfile.lock
Labels: bot, size/M

#1754 Automatic update of dependency boto3 from 1.13.4 to 1.13.5
  Pipfile.lock
Labels: bot, size/M

#1755 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/S

#1756 Automatic update of dependency boto3 from 1.13.5 to 1.13.6
  Pipfile.lock
Labels: bot, size/S

#1759 Add query to count a table
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1761 Release of version 0.22.10
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot

#1763 Automatic update of dependency sqlalchemy from 1.3.16 to 1.3.17
  Pipfile.lock
Labels: bot, size/L

#1762 Automatic update of dependency boto3 from 1.13.6 to 1.13.9
  Pipfile.lock
Labels: bot, size/S

#1765 function for checking current availability of package
  Pipfile.lock
  docs/conventions/README.md
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#1767 Automatic update of dependency boto3 from 1.13.9 to 1.13.11
  Pipfile.lock
Labels: bot, size/M

#1769 Raise NotFoundError if setting is_missing flag for non-existing package
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1764 Add Kebechet App table
  thoth/storages/data/alembic/versions/340d6e381d75_added_kebechet_installation_table.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#1771 Automatic update of dependency boto3 from 1.13.11 to 1.13.12
  Pipfile.lock
Labels: bot, size/M

#1774 Automatic update of dependency boto3 from 1.13.12 to 1.13.13
  Pipfile.lock
Labels: bot, size/L

#1770 Add is_missing optional argument to all pypackageversion queries
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#1775 Automatic update of dependency boto3 from 1.13.13 to 1.13.14
  Pipfile.lock
Labels: bot, size/M

#1776 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/XS

#1777 Automatic update of dependency boto3 from 1.13.14 to 1.13.15
  Pipfile.lock
Labels: bot, size/M

#1780 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#1783 Automatic update of dependency boto3 from 1.13.15 to 1.13.16
  Pipfile.lock
Labels: bot, size/S

#1781 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#1784 Automatic update of dependency sqlalchemy-utils from 0.36.5 to 0.36.6
  Pipfile.lock
Labels: bot, size/XS

#1782 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/XS

#1779 Release of version 0.22.11
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1786 Automatic update of dependency boto3 from 1.13.16 to 1.13.17
  Pipfile.lock
Labels: bot, size/S

#1768 Graph functions to add installations.
  docs/conventions/README.md
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#1785 add is_missing flag to depends on query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1773 Get active count
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#1788 Automatic update of dependency boto3 from 1.13.17 to 1.13.18
  Pipfile.lock
Labels: bot, size/M

#1787 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/XS

#1790 Release of version 0.22.12
  CHANGELOG.md
  thoth/storages/__init__.py
Labels: bot, size/S

#1792 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/M

#1791 Automatic update of dependency boto3 from 1.13.18 to 1.13.19
  Pipfile.lock
Labels: bot, size/S
