Repository thoth-station/storages, pull requests merged in 2021-04, with the labels that each got.

#2275 Minor improvements in docs
  README.rst
Labels: approved, size/L

#2277 Query results on Ceph based on date
  tests/base.py
  thoth/storages/ceph.py
  thoth/storages/result_base.py
Labels: approved, size/M

#2285 Remove unused comment
  thoth/storages/graph/models.py
Labels: approved, size/XS

#2286 Extend methods to handle requests
  thoth/storages/result_base.py
Labels: approved, size/M

#2283 Provide ability to include end_date in the results listing
  thoth/storages/result_base.py
Labels: approved, size/M

#2292 Provide methods for deleting data from the database
  thoth/storages/graph/postgres.py
Labels: approved, size/M
