Repository thoth-station/storages, pull requests merged in 2021-11, with the labels that each got.

#2460 Provide primitives for manipulating with CVE timestamp
  thoth/storages/data/alembic/versions/0165f03250a6_add_cve_timestamp_table.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2461 Add CVE link to CVE table
  thoth/storages/data/alembic/versions/92a5e912f877_add_cve_link_to_cve_table.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2474 Adjust flexmock import to respect new flexmock release notes
  tests/base.py
  tests/test_buildlogs.py
  tests/test_result_base.py
Labels: approved, size/XS

#2477 Use explicit exports
  thoth/storages/__init__.py
  thoth/storages/graph/__init__.py
Labels: size/M

#2480 Add distinct option to method get_python_package_version_import_packages_all
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2483 add kebechet to crossroads in docs
  docs/source/index.rst
Labels: approved, size/XS

#2486 Add missing types in function signatures
  thoth/storages/graph/postgres.py
  thoth/storages/graph/sql_base.py
Labels: approved, size/XS

#2487 Obtain environment markers based on evaluation result
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2488 Allow querying module imports
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2482 Add methods to purge old documents and store them on Ceph
  thoth/storages/graph/postgres.py
Labels: approved, size/L
