Repository thoth-station/storages, pull requests merged in 2021-08, with the labels that each got.

#2413 Set default value for only_if_package_seen
  thoth/storages/data/alembic/versions/65ae36e5c38a_extend_python_package_index_with_only_.py
Labels: approved, size/XS

#2420 Improve performance of the unsolved Python packages query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2384 add runtime_environment_name to KebechetGithubInstallation
  thoth/storages/data/alembic/versions/5c1e7425ce60_added_entry_in_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2402 Provide a method for deleting index
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2410 Add packages and populate with module names
  thoth/storages/data/alembic/versions/aba59a2fec95_add_importpackage_foundimportpackage_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L
