Repository thoth-station/storages, pull requests merged in 2021-02, with the labels that each got.

#2201 Introduce queries to query Thoth s2i container images
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2194 Create index for Thoth's s2i base image attributes
  thoth/storages/data/alembic/versions/081bee0d9587_create_index_for_thoth_s2i_specific_.py
  thoth/storages/graph/models.py
Labels: approved, sig/solvers, size/M

#2207 Fix sync solver
  thoth/storages/solvers.py
Labels: approved, lgtm, size/XS

#2197 Add queries and fix bug discovered
  thoth/storages/graph/postgres.py
Labels: approved, sig/docs, sig/solvers, size/M

#2204 Create methods for manipulating with hardware environments
  thoth/storages/graph/postgres.py
Labels: approved, lgtm, size/M

#2212 fix: the arguments for the normalize_os_version function
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2216 Sync unresolved packages from provenance checker report
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2217 Adjust query for user software stack
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2220 add marker file PEP561
  thoth/storages/py.typed
Labels: approved, size/XS

#2221 Create an adapter for persisting requests to Dependency Monkey
  thoth/storages/__init__.py
  thoth/storages/dependency_monkey_requests.py
Labels: approved, size/S
