Repository thoth-station/storages, pull requests merged in 2021-03, with the labels that each got.

#2227 update with pip, piplock, and .thoth.config dicts
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2231 Add query for number of rows in alembic table
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2230 Introduce a query for obtaining database size
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2239 Store information about images produced by AICoE CI on sync
  thoth/storages/graph/postgres.py
Labels: approved

#2238 Add information about container images stored in env variables
  thoth/storages/data/alembic/versions/cb86ec08e5ce_add_container_image_environment_.py
  thoth/storages/graph/models.py
Labels: approved

#2240 Add filters filtering based on image name
  thoth/storages/graph/postgres.py
Labels: approved, lgtm

#2244 Do not enforce Python version being set for non-external images
  thoth/storages/graph/postgres.py
Labels: lgtm, size/XS

#2255 Pin down sqlalchmey to be less than 1.4.0 version
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/L

#2258 Fix/avoid duplicate heads
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2263 Create index for depends_on considering is_missing and extras
  thoth/storages/data/alembic/versions/abb1a0a90885_create_index_depends_on_extras_and_.py
  thoth/storages/graph/models.py
Labels: approved, size/M
