Repository thoth-station/storages, pull requests merged in 2021-07, with the labels that each got.

#2379 Adjust Python package syncing logic and query for Python packages present
  thoth/storages/data/alembic/versions/95c40432360f_extend_python_package_information_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, lgtm, size/M

#2378 Remove qeb-hwt integration
  thoth/storages/graph/enums.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2386 Adjust/Add kebechet managers queries
  thoth/storages/graph/enums.py
  thoth/storages/graph/postgres.py
Labels: approved, lgtm, size/M

#2392 Adjust query and enums
  thoth/storages/graph/enums.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2396 Fix index assignment in solver rule creation
  thoth/storages/graph/postgres.py
Labels: approved, lgtm, size/XS

#2395 Extend Python package index with only_packages_seen attribute
  thoth/storages/data/alembic/versions/65ae36e5c38a_extend_python_package_index_with_only_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, priority/critical-urgent, size/M

#2404 Introduce query for obtaining trove classfiers
  thoth/storages/graph/postgres.py
Labels: approved, size/M
