Repository thoth-station/storages, pull requests merged in 2021-01, with the labels that each got.

#2154 Remove coala from requirements
  Pipfile
  Pipfile.lock
Labels: approved, size/XXL

#2156 Filter active installations in DB and fix method signature
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2155 Filter out stored requests from listing
  tests/base.py
  thoth/storages/result_base.py
Labels: approved, size/XS

#2158 Correct-output
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2160 Introduce queries to retrieve specifc document ids according to parameters
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#2164 Add prefix for buildlog documents
  tests/test_buildlogs.py
  thoth/storages/buildlogs.py
Labels: approved, size/XS

#2153 Normalization functions have been moved to common
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2170 Provide adapter for manipulating with parsed build logs
  thoth/storages/__init__.py
  thoth/storages/buildlogs_parsed.py
  thoth/storages/data/alembic/versions/91620576525b_remove_buildlog_analyzers.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/sync.py
Labels: approved, size/L

#2171 Add flters for solver query to retrieve document ids by error
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2183 remove call to install amcheck on postgres
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2187 Do not sync Dependency Monkey document if any error is reported
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2192 Sync Thoth specific environment variables from package-extract runs
  thoth/storages/data/alembic/versions/b957aa9cce3e_introduce_thoth_specific_entries_found_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2193 Move Thoth s2i specific env vars to software environment models
  thoth/storages/data/alembic/versions/f1824f0c1afa_move_thoth_s2i_information_to_software_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2195 Create query for querying Thoth's s2i container image symbols
  thoth/storages/graph/postgres.py
Labels: approved, size/S
