Repository thoth-station/storages, pull requests merged in 2021-05, with the labels that each got.

#2300 Fix referenced variable
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2293 get or create github kebechet installation
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2302 Make at least one filter mandatory when deleting package-extract runs
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2311 update the prow jobs resource requests
  .prow.yaml
Labels: approved, size/S

#2310 Provide force_sync option to solver syncing logic
  thoth/storages/graph/postgres.py
  thoth/storages/sync.py
Labels: approved, size/M
