Repository thoth-station/storages, pull requests merged in 2021-12, with the labels that each got.

#2499 Fix v0.61.0 changelog computed
  CHANGELOG.md
Labels: approved, size/XXL

#2508 Introduce a query for obtaining environments used to solve a package
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2511 Allow syncing non-Thoth env variables from package-extract resul
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2513 make Package Extract Run table image size column datatype BigInteger
  thoth/storages/data/alembic/versions/b718c0f8bc53_make_package_extract_image_size_columb_.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#2512 Extend get_software_environments_all query to provide also package_extract_run id and datetime.
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2517 Fix condition to identify env vars
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2523 Allow sorting and pagination of get_python_package_version_names_all
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2519 Fix return type
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2525 Introduce query for obtaining solver documents for the given package
  thoth/storages/graph/postgres.py
Labels: approved, size/M
