Repository thoth-station/storages, pull requests merged in 2021-06, with the labels that each got.

#2314 Fix only_if_package_seen logic handling
  thoth/storages/graph/postgres.py
Labels: approved, priority/critical-urgent, size/S

#2313 Introduce routines for manipulating with rules
  Pipfile
  Pipfile.lock
  thoth/storages/data/alembic/versions/db6290ac490d_create_python_package_entity_rules.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#2320 Adjust CVE model to consume vulnerabilities from pypa/advisory-db
  thoth/storages/data/alembic/versions/50081eea5da2_adjust_cve_model_to_consume_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2321 Create a query for listing rules assigned for a specific package
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2325 Cache solver rules retrieval
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2330 Implement adapter for accessing Argo Workflow logs
  thoth/storages/__init__.py
  thoth/storages/exceptions.py
  thoth/storages/logs.py
Labels: approved, size/M

#2335 missing model import for ExternalPythonSoftwareStack
  thoth/storages/graph/postgres.py
Labels: approved, lgtm, size/XS

#2337 Fix unknown index_url in entity when a rule is assigned
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2347 Add method for CVE count
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2344 updates from the template project
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .pre-commit-config.yaml
  .prow.yaml
Labels: bot, size/M

#2351 Consistency for OS name in tables and methods
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2354 Optimize query platform
  thoth/storages/data/alembic/versions/5d41082a1433_add_platform_with_enums_to_dependson_.py
  thoth/storages/data/alembic/versions/894ddaef0c43_remove_platform_from_depends_on.py
  thoth/storages/graph/enums.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, lgtm, size/L

#2358 updates from the template project
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, size/S

#2359 Introduce query for retrieving RPM packages for a container image analysis
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2364 Introduce query for obtaining last container image analysis
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2363 Cache query for retrieving RPM versions from the database
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2356 Cache S2I image symbols query
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2368 Introduce query for index bloat data
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#2372 set badges for easy access to content
  README.rst
Labels: approved, size/S

#2346 add query for filtering git app installations by software environment…
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2375 Deprecated the platform column form the dependsOn table
  thoth/storages/data/alembic/versions/5d41082a1433_add_platform_with_enums_to_dependson_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M
