Repository thoth-station/storages, pull requests merged in 2021-09, with the labels that each got.

#2427 Modify get_solved_python_package_versions_software_environment_all method
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2426 Raise if no matching package for the given import was found
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2401 Unloop join to index in the unsolved query
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#2431 Revert removing join index table from query
  thoth/storages/graph/postgres.py
Labels: approved, size/L
