Repository thoth-station/storages, pull requests merged in 2022-01, with the labels that each got.

#2528 Introduce a query for counting software environments
  thoth/storages/graph/postgres.py
Labels: approved, size/L

#2532 Provide a method that counts number of Python package names
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2537 add query for number of software stacks maintained by kebechet
  .pre-commit-config.yaml
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2542 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#2543 add break statement and remove unique slug constraint
  thoth/storages/data/alembic/versions/c427c501f966_remove_unique_constraint_from_slug_in_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2546 Rename thoth_s2i_* in database schema
  thoth/storages/data/alembic/versions/930b47e27b6c_rename_thoth_s2i_columns.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2549 Specify command to sync local database instance in documentation
  README.rst
Labels: approved, size/M

#2550 Modify query of containerized environments to get specific content
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2555 Add my username to maintainers
  .thoth.yaml
Labels: approved, size/XS

#2556 Fix formatting of README
  README.rst
Labels: approved, size/S

#2565 Instructions for accessing Thoth's public database on opf-datacatalog
  README.rst
Labels: approved, size/S
