Repository thoth-station/storages, pull requests merged in 2022-08, with the labels that each got.

#2660 Enable pydocstyle pre-commit hook
  .pre-commit-config.yaml
  docs/source/conf.py
  setup.py
  tests/base.py
  tests/test_analyses.py
  tests/test_ceph.py
  tests/test_result_base.py
  tests/test_solvers.py
  thoth/storages/data/alembic/env.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
  thoth/storages/inspections.py
  thoth/storages/security_indicators.py
Labels: approved, size/L, kind/cleanup

#2677 Make _iter_dates_prefix_addition a static method
  thoth/storages/ceph.py
  thoth/storages/result_base.py
  thoth/storages/solvers.py
Labels: approved, size/S

#2647 added thoth-license-solver
  Pipfile
  thoth/storages/data/alembic/versions/2a4632197512_added_license_solver.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2676 Retrieve TTL of cached documents
  thoth/storages/ceph.py
  thoth/storages/ceph_cache.py
Labels: size/S
