Repository thoth-station/storages, pull requests merged in 2022-02, with the labels that each got.

#2575 Fix container image query
  thoth/storages/graph/postgres.py
Labels: size/S

#2580 Fix Ceph variable names and add examples
  README.rst
Labels: approved, size/S

#2583 Fix adapter name for package-extract documents
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2586 Provide a way to iterate over solvers of a specific type
  thoth/storages/result_base.py
  thoth/storages/solvers.py
Labels: approved, size/M

#2587 Add myself to approvers
  OWNERS
Labels: approved, size/XS

#2581 add environment name to get_keb_gh_installation_info
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2593 remove unusued parameter
  thoth/storages/graph/postgres.py
Labels: approved, size/XS, lgtm

#2569 Retrieve datetime of last synced solver
  thoth/storages/graph/postgres.py
Labels: approved, size/S

#2592 Query datetime of last container image analysis synced in the database
  thoth/storages/graph/postgres.py
Labels: approved, size/XS

#2601 Fix typo
  README.rst
Labels: approved, size/XS

#2599 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .prow.yaml
  thoth/storages/graph/postgres.py
Labels: approved, size/M
