Repository thoth-station/storages, pull requests merged in 2022-09, with the labels that each got.

#2702 Convert ceph datetime object to be offset-aware
  thoth/storages/ceph_cache.py
Labels: approved, size/XS, lgtm

#2709 Set license solver params as unique constraint to reduce duplication
  thoth/storages/data/alembic/versions/7f7411e247d6_migrate_license_solver_data.py
  thoth/storages/graph/models.py
Labels: approved, size/M

#2718 Fix timezone import in ceph cache
  thoth/storages/ceph_cache.py
Labels: size/XS
