Repository thoth-station/storages, pull requests merged in 2022-03, with the labels that each got.

#2605 update to latest pgsql container image
  .pre-commit-config.yaml
  README.rst
  docker-compose.yaml
Labels: approved, size/S

#2609 Fix method to iterate on thoth files
  thoth/storages/result_base.py
Labels: approved, size/XS

#2579 Adjust query for metadata due to change in schema
  thoth/storages/graph/postgres.py
Labels: approved, size/S, do-not-merge/hold

#2568 New column entry to separate source from project url
  thoth/storages/data/alembic/versions/2b787ddad4a4_separate_the_project_url_column_from_.py
  thoth/storages/graph/models.py
  thoth/storages/graph/postgres.py
Labels: approved, size/M

#2602 update metadata.id instead of passing it to 'create_ppv'
  thoth/storages/graph/postgres.py
Labels: approved, size/XS
