Repository thoth-station/storages, pull requests merged in 2023-01, with the labels that each got.

#2752 Add Pep as an approver / reviewer
  OWNERS
Labels: approved, size/XS, lgtm

#2751 :face_in_clouds: Fix the sync_documents formatting
  thoth/storages/sync.py
Labels: approved, size/S, lgtm

#2749 Fix new data causing PythonPackageVersion class IntegrityError
  thoth/storages/graph/postgres.py
Labels: size/XS, lgtm

#2748 Fix software_environment_id null violation
  thoth/storages/data/alembic/versions/bf9ea2a38b01_fix_null_values_considered_as_distinct_.py
  thoth/storages/graph/models.py
Labels: lgtm

#2758 Fix docs sync, take 2
  thoth/storages/sync.py
Labels: approved, size/XS, lgtm
